// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Servers               `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Log           *Log                   `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Mh            *Mh                    `protobuf:"bytes,4,opt,name=mh,proto3" json:"mh,omitempty"`
	Nacos         *Nacos                 `protobuf:"bytes,101,opt,name=nacos,proto3" json:"nacos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Servers {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetMh() *Mh {
	if x != nil {
		return x.Mh
	}
	return nil
}

func (x *Bootstrap) GetNacos() *Nacos {
	if x != nil {
		return x.Nacos
	}
	return nil
}

type Mh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spider        *Spider                `protobuf:"bytes,1,opt,name=spider,proto3" json:"spider,omitempty"`
	Storage       *Storage               `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	Sync          *Sync                  `protobuf:"bytes,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mh) Reset() {
	*x = Mh{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mh) ProtoMessage() {}

func (x *Mh) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mh.ProtoReflect.Descriptor instead.
func (*Mh) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Mh) GetSpider() *Spider {
	if x != nil {
		return x.Spider
	}
	return nil
}

func (x *Mh) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Mh) GetSync() *Sync {
	if x != nil {
		return x.Sync
	}
	return nil
}

type Spider struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Authority              string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	BookListUrlTemplate    string                 `protobuf:"bytes,2,opt,name=book_list_url_template,json=bookListUrlTemplate,proto3" json:"book_list_url_template,omitempty"`
	BookDetailUrlTemplate  string                 `protobuf:"bytes,3,opt,name=book_detail_url_template,json=bookDetailUrlTemplate,proto3" json:"book_detail_url_template,omitempty"`
	ChapterUrlTemplate     string                 `protobuf:"bytes,4,opt,name=chapter_url_template,json=chapterUrlTemplate,proto3" json:"chapter_url_template,omitempty"`
	ChapterRefererTemplate string                 `protobuf:"bytes,5,opt,name=chapter_referer_template,json=chapterRefererTemplate,proto3" json:"chapter_referer_template,omitempty"`
	RequestTimeoutSeconds  int32                  `protobuf:"varint,6,opt,name=request_timeout_seconds,json=requestTimeoutSeconds,proto3" json:"request_timeout_seconds,omitempty"`
	RetryTimes             int32                  `protobuf:"varint,7,opt,name=retry_times,json=retryTimes,proto3" json:"retry_times,omitempty"`
	MinDelayMs             int32                  `protobuf:"varint,8,opt,name=min_delay_ms,json=minDelayMs,proto3" json:"min_delay_ms,omitempty"`
	MaxDelayMs             int32                  `protobuf:"varint,9,opt,name=max_delay_ms,json=maxDelayMs,proto3" json:"max_delay_ms,omitempty"`
	BootstrapBookListPages int32                  `protobuf:"varint,10,opt,name=bootstrap_book_list_pages,json=bootstrapBookListPages,proto3" json:"bootstrap_book_list_pages,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Spider) Reset() {
	*x = Spider{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spider) ProtoMessage() {}

func (x *Spider) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spider.ProtoReflect.Descriptor instead.
func (*Spider) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Spider) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *Spider) GetBookListUrlTemplate() string {
	if x != nil {
		return x.BookListUrlTemplate
	}
	return ""
}

func (x *Spider) GetBookDetailUrlTemplate() string {
	if x != nil {
		return x.BookDetailUrlTemplate
	}
	return ""
}

func (x *Spider) GetChapterUrlTemplate() string {
	if x != nil {
		return x.ChapterUrlTemplate
	}
	return ""
}

func (x *Spider) GetChapterRefererTemplate() string {
	if x != nil {
		return x.ChapterRefererTemplate
	}
	return ""
}

func (x *Spider) GetRequestTimeoutSeconds() int32 {
	if x != nil {
		return x.RequestTimeoutSeconds
	}
	return 0
}

func (x *Spider) GetRetryTimes() int32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

func (x *Spider) GetMinDelayMs() int32 {
	if x != nil {
		return x.MinDelayMs
	}
	return 0
}

func (x *Spider) GetMaxDelayMs() int32 {
	if x != nil {
		return x.MaxDelayMs
	}
	return 0
}

func (x *Spider) GetBootstrapBookListPages() int32 {
	if x != nil {
		return x.BootstrapBookListPages
	}
	return 0
}

type Storage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey       string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey       string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Secure          bool                   `protobuf:"varint,4,opt,name=secure,proto3" json:"secure,omitempty"`
	Bucket          string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	PublicBaseUrl   string                 `protobuf:"bytes,6,opt,name=public_base_url,json=publicBaseUrl,proto3" json:"public_base_url,omitempty"`
	DefaultCoverUrl string                 `protobuf:"bytes,7,opt,name=default_cover_url,json=defaultCoverUrl,proto3" json:"default_cover_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Storage) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Storage) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Storage) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Storage) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Storage) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Storage) GetPublicBaseUrl() string {
	if x != nil {
		return x.PublicBaseUrl
	}
	return ""
}

func (x *Storage) GetDefaultCoverUrl() string {
	if x != nil {
		return x.DefaultCoverUrl
	}
	return ""
}

type Sync struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	StateId                    string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	StopAfterConsecutiveErrors int32                  `protobuf:"varint,2,opt,name=stop_after_consecutive_errors,json=stopAfterConsecutiveErrors,proto3" json:"stop_after_consecutive_errors,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Sync) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *Sync) GetStopAfterConsecutiveErrors() int32 {
	if x != nil {
		return x.StopAfterConsecutiveErrors
	}
	return 0
}

type RedisCluster struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redis Cluster 的 seed 节点列表（至少 1 个，建议填 3 个）
	// 例：["172.31.32.200:7001","172.31.32.200:7002","172.31.32.200:7003"]
	Seeds []string `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	// requirepass / masterauth
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 是否启用 READONLY（允许读副本）
	ReadOnly      bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisCluster) Reset() {
	*x = RedisCluster{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisCluster) ProtoMessage() {}

func (x *RedisCluster) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisCluster.ProtoReflect.Descriptor instead.
func (*RedisCluster) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{5}
}

func (x *RedisCluster) GetSeeds() []string {
	if x != nil {
		return x.Seeds
	}
	return nil
}

func (x *RedisCluster) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisCluster) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type Nacos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          uint64                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	LogDir        string                 `protobuf:"bytes,5,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	ClusterName   string                 `protobuf:"bytes,6,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	NamespaceId   string                 `protobuf:"bytes,7,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DataId        string                 `protobuf:"bytes,9,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Weight        int32                  `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	DataIds       []string               `protobuf:"bytes,11,rep,name=data_ids,json=dataIds,proto3" json:"data_ids,omitempty"` // 支持多个 data_id，按顺序后面的会覆盖前面的参数，data_id 同时设置实际插入 data_ids 第一位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nacos) Reset() {
	*x = Nacos{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nacos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nacos) ProtoMessage() {}

func (x *Nacos) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nacos.ProtoReflect.Descriptor instead.
func (*Nacos) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Nacos) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Nacos) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Nacos) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Nacos) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Nacos) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Nacos) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Nacos) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *Nacos) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Nacos) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *Nacos) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Nacos) GetDataIds() []string {
	if x != nil {
		return x.DataIds
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableStdLog bool                   `protobuf:"varint,1,opt,name=disable_std_log,json=disableStdLog,proto3" json:"disable_std_log,omitempty"` // 禁用标准输出
	LogDir        string                 `protobuf:"bytes,2,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`                         // 文件日志路径
	LogFilename   string                 `protobuf:"bytes,3,opt,name=log_filename,json=logFilename,proto3" json:"log_filename,omitempty"`          // 文件日志路径
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`                                         // DEBUG / INFO / WARNING / ERROR
	MaxSizeMb     int32                  `protobuf:"varint,10,opt,name=max_size_mb,json=maxSizeMb,proto3" json:"max_size_mb,omitempty"`            // 单文件上限 (MB)，0 表示默认 100
	MaxBackups    int32                  `protobuf:"varint,11,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`           // 最多保留文件数，0 不限制
	MaxAgeDays    int32                  `protobuf:"varint,12,opt,name=max_age_days,json=maxAgeDays,proto3" json:"max_age_days,omitempty"`         // 最多保留天数，0 不限制
	Compress      bool                   `protobuf:"varint,13,opt,name=compress,proto3" json:"compress,omitempty"`                                 // 历史文件是否 gzip
	RotateDaily   bool                   `protobuf:"varint,14,opt,name=rotate_daily,json=rotateDaily,proto3" json:"rotate_daily,omitempty"`        // 按天轮转；false 为按大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Log) GetDisableStdLog() bool {
	if x != nil {
		return x.DisableStdLog
	}
	return false
}

func (x *Log) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Log) GetLogFilename() string {
	if x != nil {
		return x.LogFilename
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMaxSizeMb() int32 {
	if x != nil {
		return x.MaxSizeMb
	}
	return 0
}

func (x *Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log) GetMaxAgeDays() int32 {
	if x != nil {
		return x.MaxAgeDays
	}
	return 0
}

func (x *Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *Log) GetRotateDaily() bool {
	if x != nil {
		return x.RotateDaily
	}
	return false
}

type Servers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server                `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Http          *Server                `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Servers) Reset() {
	*x = Servers{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Servers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Servers) ProtoMessage() {}

func (x *Servers) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Servers.ProtoReflect.Descriptor instead.
func (*Servers) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Servers) GetGrpc() *Server {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Servers) GetHttp() *Server {
	if x != nil {
		return x.Http
	}
	return nil
}

type Server struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Addr           string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Network        string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	PublicEndpoint string                 `protobuf:"bytes,4,opt,name=public_endpoint,json=publicEndpoint,proto3" json:"public_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Server) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Server) GetPublicEndpoint() string {
	if x != nil {
		return x.PublicEndpoint
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postgres      *Postgres              `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	RedisCluster  *RedisCluster          `protobuf:"bytes,2,opt,name=redis_cluster,json=redisCluster,proto3" json:"redis_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Data) GetPostgres() *Postgres {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *Data) GetRedisCluster() *RedisCluster {
	if x != nil {
		return x.RedisCluster
	}
	return nil
}

type Postgres struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Postgres) Reset() {
	*x = Postgres{}
	mi := &file_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Postgres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Postgres) ProtoMessage() {}

func (x *Postgres) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Postgres.ProtoReflect.Descriptor instead.
func (*Postgres) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Postgres) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x06app.mh\x1a\x1egoogle/protobuf/duration.proto\"\xb6\x01\n" +
	"\tBootstrap\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.app.mh.ServersR\x06server\x12\x1d\n" +
	"\x03log\x18\x02 \x01(\v2\v.app.mh.LogR\x03log\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.app.mh.DataR\x04data\x12\x1a\n" +
	"\x02mh\x18\x04 \x01(\v2\n" +
	".app.mh.MhR\x02mh\x12#\n" +
	"\x05nacos\x18e \x01(\v2\r.app.mh.NacosR\x05nacos\"y\n" +
	"\x02Mh\x12&\n" +
	"\x06spider\x18\x01 \x01(\v2\x0e.app.mh.SpiderR\x06spider\x12)\n" +
	"\astorage\x18\x02 \x01(\v2\x0f.app.mh.StorageR\astorage\x12 \n" +
	"\x04sync\x18\x03 \x01(\v2\f.app.mh.SyncR\x04sync\"\xd8\x03\n" +
	"\x06Spider\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x123\n" +
	"\x16book_list_url_template\x18\x02 \x01(\tR\x13bookListUrlTemplate\x127\n" +
	"\x18book_detail_url_template\x18\x03 \x01(\tR\x15bookDetailUrlTemplate\x120\n" +
	"\x14chapter_url_template\x18\x04 \x01(\tR\x12chapterUrlTemplate\x128\n" +
	"\x18chapter_referer_template\x18\x05 \x01(\tR\x16chapterRefererTemplate\x126\n" +
	"\x17request_timeout_seconds\x18\x06 \x01(\x05R\x15requestTimeoutSeconds\x12\x1f\n" +
	"\vretry_times\x18\a \x01(\x05R\n" +
	"retryTimes\x12 \n" +
	"\fmin_delay_ms\x18\b \x01(\x05R\n" +
	"minDelayMs\x12 \n" +
	"\fmax_delay_ms\x18\t \x01(\x05R\n" +
	"maxDelayMs\x129\n" +
	"\x19bootstrap_book_list_pages\x18\n" +
	" \x01(\x05R\x16bootstrapBookListPages\"\xe7\x01\n" +
	"\aStorage\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06secure\x18\x04 \x01(\bR\x06secure\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12&\n" +
	"\x0fpublic_base_url\x18\x06 \x01(\tR\rpublicBaseUrl\x12*\n" +
	"\x11default_cover_url\x18\a \x01(\tR\x0fdefaultCoverUrl\"d\n" +
	"\x04Sync\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12A\n" +
	"\x1dstop_after_consecutive_errors\x18\x02 \x01(\x05R\x1astopAfterConsecutiveErrors\"]\n" +
	"\fRedisCluster\x12\x14\n" +
	"\x05seeds\x18\x01 \x03(\tR\x05seeds\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\xad\x02\n" +
	"\x05Nacos\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x04R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\alog_dir\x18\x05 \x01(\tR\x06logDir\x12!\n" +
	"\fcluster_name\x18\x06 \x01(\tR\vclusterName\x12!\n" +
	"\fnamespace_id\x18\a \x01(\tR\vnamespaceId\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\tR\agroupId\x12\x17\n" +
	"\adata_id\x18\t \x01(\tR\x06dataId\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x05R\x06weight\x12\x19\n" +
	"\bdata_ids\x18\v \x03(\tR\adataIds\"\xa1\x02\n" +
	"\x03Log\x12&\n" +
	"\x0fdisable_std_log\x18\x01 \x01(\bR\rdisableStdLog\x12\x17\n" +
	"\alog_dir\x18\x02 \x01(\tR\x06logDir\x12!\n" +
	"\flog_filename\x18\x03 \x01(\tR\vlogFilename\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x1e\n" +
	"\vmax_size_mb\x18\n" +
	" \x01(\x05R\tmaxSizeMb\x12\x1f\n" +
	"\vmax_backups\x18\v \x01(\x05R\n" +
	"maxBackups\x12 \n" +
	"\fmax_age_days\x18\f \x01(\x05R\n" +
	"maxAgeDays\x12\x1a\n" +
	"\bcompress\x18\r \x01(\bR\bcompress\x12!\n" +
	"\frotate_daily\x18\x0e \x01(\bR\vrotateDaily\"Q\n" +
	"\aServers\x12\"\n" +
	"\x04grpc\x18\x01 \x01(\v2\x0e.app.mh.ServerR\x04grpc\x12\"\n" +
	"\x04http\x18\x02 \x01(\v2\x0e.app.mh.ServerR\x04http\"\x94\x01\n" +
	"\x06Server\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12'\n" +
	"\x0fpublic_endpoint\x18\x04 \x01(\tR\x0epublicEndpoint\"o\n" +
	"\x04Data\x12,\n" +
	"\bpostgres\x18\x01 \x01(\v2\x10.app.mh.PostgresR\bpostgres\x129\n" +
	"\rredis_cluster\x18\x02 \x01(\v2\x14.app.mh.RedisClusterR\fredisCluster\"\x1c\n" +
	"\bPostgres\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsnB\x0fZ\rinternal/confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: app.mh.Bootstrap
	(*Mh)(nil),                  // 1: app.mh.Mh
	(*Spider)(nil),              // 2: app.mh.Spider
	(*Storage)(nil),             // 3: app.mh.Storage
	(*Sync)(nil),                // 4: app.mh.Sync
	(*RedisCluster)(nil),        // 5: app.mh.RedisCluster
	(*Nacos)(nil),               // 6: app.mh.Nacos
	(*Log)(nil),                 // 7: app.mh.Log
	(*Servers)(nil),             // 8: app.mh.Servers
	(*Server)(nil),              // 9: app.mh.Server
	(*Data)(nil),                // 10: app.mh.Data
	(*Postgres)(nil),            // 11: app.mh.Postgres
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	8,  // 0: app.mh.Bootstrap.server:type_name -> app.mh.Servers
	7,  // 1: app.mh.Bootstrap.log:type_name -> app.mh.Log
	10, // 2: app.mh.Bootstrap.data:type_name -> app.mh.Data
	1,  // 3: app.mh.Bootstrap.mh:type_name -> app.mh.Mh
	6,  // 4: app.mh.Bootstrap.nacos:type_name -> app.mh.Nacos
	2,  // 5: app.mh.Mh.spider:type_name -> app.mh.Spider
	3,  // 6: app.mh.Mh.storage:type_name -> app.mh.Storage
	4,  // 7: app.mh.Mh.sync:type_name -> app.mh.Sync
	9,  // 8: app.mh.Servers.grpc:type_name -> app.mh.Server
	9,  // 9: app.mh.Servers.http:type_name -> app.mh.Server
	12, // 10: app.mh.Server.timeout:type_name -> google.protobuf.Duration
	11, // 11: app.mh.Data.postgres:type_name -> app.mh.Postgres
	5,  // 12: app.mh.Data.redis_cluster:type_name -> app.mh.RedisCluster
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
