// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/app_init"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/conf"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/data"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/server"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/service"
	"github.com/jeffinity/singularity/kratosx"
	"github.com/jeffinity/singularity/nacosx"
	"sync"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(pcID kratosx.ServiceID, root context.Context, c *conf.Bootstrap, wg *sync.WaitGroup, logger log.Logger) (*kratos.App, func(), error) {
	healthService := service.NewHealthService(logger, c)
	db, err := data.NewPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(c, db, logger)
	if err != nil {
		return nil, nil, err
	}
	assetRepo := data.NewAssetRepo(dataData, logger)
	loanRepo := data.NewLoanRepo(dataData, logger)
	ledgerRepo := data.NewLedgerRepo(dataData, logger)
	bookkeepingService := service.NewBookkeepingService(assetRepo, loanRepo, ledgerRepo, logger)
	grpcServer := server.NewGRPCServer(c, healthService, bookkeepingService, logger)
	httpServer := server.NewHTTPServer(c, healthService, bookkeepingService, logger)
	nacosxConf := app_init.NewNacosConf(c)
	iNamingClient, err := nacosx.NewNamingClient(nacosxConf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registry, err := nacosx.NewRegistryEngine(nacosxConf, iNamingClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, err := newApp(pcID, logger, c, grpcServer, httpServer, registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
