// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"context"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/mh/internal/conf"
	"github.com/jeffinity/oculus/app/mh/internal/data"
	"github.com/jeffinity/singularity/kratosx"
	"sync"
)

// Injectors from wire.go:

func InitTestResource(pcID kratosx.ServiceID, logger log.Logger, root context.Context, wg *sync.WaitGroup, c *conf.Bootstrap) (*Resource, func(), error) {
	db, err := data.NewPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewMinio(c)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(c, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	resource := newTestResource(root, logger, dataData)
	return resource, func() {
		cleanup()
	}, nil
}
