// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/squirrel/v1/squirrel.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSquirrelServiceClearManualReviews = "/api.squirrel.v1.SquirrelService/ClearManualReviews"
const OperationSquirrelServiceClearSectionData = "/api.squirrel.v1.SquirrelService/ClearSectionData"
const OperationSquirrelServiceCreateTask = "/api.squirrel.v1.SquirrelService/CreateTask"
const OperationSquirrelServiceDeleteManualRemarkOption = "/api.squirrel.v1.SquirrelService/DeleteManualRemarkOption"
const OperationSquirrelServiceDeleteManualReview = "/api.squirrel.v1.SquirrelService/DeleteManualReview"
const OperationSquirrelServiceDeleteTask = "/api.squirrel.v1.SquirrelService/DeleteTask"
const OperationSquirrelServiceGetReconcileStatus = "/api.squirrel.v1.SquirrelService/GetReconcileStatus"
const OperationSquirrelServiceListManualRemarkOptions = "/api.squirrel.v1.SquirrelService/ListManualRemarkOptions"
const OperationSquirrelServiceListReconcileRows = "/api.squirrel.v1.SquirrelService/ListReconcileRows"
const OperationSquirrelServiceListSectionRows = "/api.squirrel.v1.SquirrelService/ListSectionRows"
const OperationSquirrelServiceListTasks = "/api.squirrel.v1.SquirrelService/ListTasks"
const OperationSquirrelServiceStartReconcile = "/api.squirrel.v1.SquirrelService/StartReconcile"
const OperationSquirrelServiceUploadSectionFile = "/api.squirrel.v1.SquirrelService/UploadSectionFile"
const OperationSquirrelServiceUpsertManualReview = "/api.squirrel.v1.SquirrelService/UpsertManualReview"

type SquirrelServiceHTTPServer interface {
	ClearManualReviews(context.Context, *ClearManualReviewsRequest) (*ClearManualReviewsReply, error)
	ClearSectionData(context.Context, *ClearSectionDataRequest) (*ClearSectionDataReply, error)
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error)
	DeleteManualRemarkOption(context.Context, *DeleteManualRemarkOptionRequest) (*DeleteManualRemarkOptionReply, error)
	DeleteManualReview(context.Context, *DeleteManualReviewRequest) (*DeleteManualReviewReply, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error)
	GetReconcileStatus(context.Context, *GetReconcileStatusRequest) (*GetReconcileStatusReply, error)
	ListManualRemarkOptions(context.Context, *ListManualRemarkOptionsRequest) (*ListManualRemarkOptionsReply, error)
	ListReconcileRows(context.Context, *ListReconcileRowsRequest) (*ListReconcileRowsReply, error)
	ListSectionRows(context.Context, *ListSectionRowsRequest) (*ListSectionRowsReply, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	StartReconcile(context.Context, *StartReconcileRequest) (*StartReconcileReply, error)
	UploadSectionFile(context.Context, *UploadSectionFileRequest) (*UploadSectionFileReply, error)
	UpsertManualReview(context.Context, *UpsertManualReviewRequest) (*UpsertManualReviewReply, error)
}

func RegisterSquirrelServiceHTTPServer(s *http.Server, srv SquirrelServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/squirrel/tasks", _SquirrelService_ListTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks", _SquirrelService_CreateTask0_HTTP_Handler(srv))
	r.DELETE("/api/v1/squirrel/tasks/{task_id}", _SquirrelService_DeleteTask0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks/{task_id}/sections/{section}/upload", _SquirrelService_UploadSectionFile0_HTTP_Handler(srv))
	r.GET("/api/v1/squirrel/tasks/{task_id}/sections/{section}/rows", _SquirrelService_ListSectionRows0_HTTP_Handler(srv))
	r.DELETE("/api/v1/squirrel/tasks/{task_id}/sections/{section}/data", _SquirrelService_ClearSectionData0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks/{task_id}/reconcile:start", _SquirrelService_StartReconcile0_HTTP_Handler(srv))
	r.GET("/api/v1/squirrel/tasks/{task_id}/reconcile/status", _SquirrelService_GetReconcileStatus0_HTTP_Handler(srv))
	r.GET("/api/v1/squirrel/tasks/{task_id}/reconcile/rows", _SquirrelService_ListReconcileRows0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks/{task_id}/manual-reviews:upsert", _SquirrelService_UpsertManualReview0_HTTP_Handler(srv))
	r.DELETE("/api/v1/squirrel/tasks/{task_id}/manual-reviews", _SquirrelService_ClearManualReviews0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks/{task_id}/manual-reviews:delete", _SquirrelService_DeleteManualReview0_HTTP_Handler(srv))
	r.GET("/api/v1/squirrel/tasks/{task_id}/manual-remark-options", _SquirrelService_ListManualRemarkOptions0_HTTP_Handler(srv))
	r.POST("/api/v1/squirrel/tasks/{task_id}/manual-remark-options:delete", _SquirrelService_DeleteManualRemarkOption0_HTTP_Handler(srv))
}

func _SquirrelService_ListTasks0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_CreateTask0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTaskReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_DeleteTask0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*DeleteTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTaskReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_UploadSectionFile0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadSectionFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceUploadSectionFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadSectionFile(ctx, req.(*UploadSectionFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadSectionFileReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_ListSectionRows0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSectionRowsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceListSectionRows)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSectionRows(ctx, req.(*ListSectionRowsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSectionRowsReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_ClearSectionData0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearSectionDataRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceClearSectionData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearSectionData(ctx, req.(*ClearSectionDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearSectionDataReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_StartReconcile0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartReconcileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceStartReconcile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartReconcile(ctx, req.(*StartReconcileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartReconcileReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_GetReconcileStatus0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReconcileStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceGetReconcileStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReconcileStatus(ctx, req.(*GetReconcileStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReconcileStatusReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_ListReconcileRows0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReconcileRowsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceListReconcileRows)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReconcileRows(ctx, req.(*ListReconcileRowsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReconcileRowsReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_UpsertManualReview0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertManualReviewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceUpsertManualReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertManualReview(ctx, req.(*UpsertManualReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertManualReviewReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_ClearManualReviews0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearManualReviewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceClearManualReviews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearManualReviews(ctx, req.(*ClearManualReviewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearManualReviewsReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_DeleteManualReview0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteManualReviewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceDeleteManualReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteManualReview(ctx, req.(*DeleteManualReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteManualReviewReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_ListManualRemarkOptions0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListManualRemarkOptionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceListManualRemarkOptions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListManualRemarkOptions(ctx, req.(*ListManualRemarkOptionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListManualRemarkOptionsReply)
		return ctx.Result(200, reply)
	}
}

func _SquirrelService_DeleteManualRemarkOption0_HTTP_Handler(srv SquirrelServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteManualRemarkOptionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSquirrelServiceDeleteManualRemarkOption)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteManualRemarkOption(ctx, req.(*DeleteManualRemarkOptionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteManualRemarkOptionReply)
		return ctx.Result(200, reply)
	}
}

type SquirrelServiceHTTPClient interface {
	ClearManualReviews(ctx context.Context, req *ClearManualReviewsRequest, opts ...http.CallOption) (rsp *ClearManualReviewsReply, err error)
	ClearSectionData(ctx context.Context, req *ClearSectionDataRequest, opts ...http.CallOption) (rsp *ClearSectionDataReply, err error)
	CreateTask(ctx context.Context, req *CreateTaskRequest, opts ...http.CallOption) (rsp *CreateTaskReply, err error)
	DeleteManualRemarkOption(ctx context.Context, req *DeleteManualRemarkOptionRequest, opts ...http.CallOption) (rsp *DeleteManualRemarkOptionReply, err error)
	DeleteManualReview(ctx context.Context, req *DeleteManualReviewRequest, opts ...http.CallOption) (rsp *DeleteManualReviewReply, err error)
	DeleteTask(ctx context.Context, req *DeleteTaskRequest, opts ...http.CallOption) (rsp *DeleteTaskReply, err error)
	GetReconcileStatus(ctx context.Context, req *GetReconcileStatusRequest, opts ...http.CallOption) (rsp *GetReconcileStatusReply, err error)
	ListManualRemarkOptions(ctx context.Context, req *ListManualRemarkOptionsRequest, opts ...http.CallOption) (rsp *ListManualRemarkOptionsReply, err error)
	ListReconcileRows(ctx context.Context, req *ListReconcileRowsRequest, opts ...http.CallOption) (rsp *ListReconcileRowsReply, err error)
	ListSectionRows(ctx context.Context, req *ListSectionRowsRequest, opts ...http.CallOption) (rsp *ListSectionRowsReply, err error)
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksReply, err error)
	StartReconcile(ctx context.Context, req *StartReconcileRequest, opts ...http.CallOption) (rsp *StartReconcileReply, err error)
	UploadSectionFile(ctx context.Context, req *UploadSectionFileRequest, opts ...http.CallOption) (rsp *UploadSectionFileReply, err error)
	UpsertManualReview(ctx context.Context, req *UpsertManualReviewRequest, opts ...http.CallOption) (rsp *UpsertManualReviewReply, err error)
}

type SquirrelServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSquirrelServiceHTTPClient(client *http.Client) SquirrelServiceHTTPClient {
	return &SquirrelServiceHTTPClientImpl{client}
}

func (c *SquirrelServiceHTTPClientImpl) ClearManualReviews(ctx context.Context, in *ClearManualReviewsRequest, opts ...http.CallOption) (*ClearManualReviewsReply, error) {
	var out ClearManualReviewsReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/manual-reviews"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceClearManualReviews))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) ClearSectionData(ctx context.Context, in *ClearSectionDataRequest, opts ...http.CallOption) (*ClearSectionDataReply, error) {
	var out ClearSectionDataReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/sections/{section}/data"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceClearSectionData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...http.CallOption) (*CreateTaskReply, error) {
	var out CreateTaskReply
	pattern := "/api/v1/squirrel/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) DeleteManualRemarkOption(ctx context.Context, in *DeleteManualRemarkOptionRequest, opts ...http.CallOption) (*DeleteManualRemarkOptionReply, error) {
	var out DeleteManualRemarkOptionReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/manual-remark-options:delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceDeleteManualRemarkOption))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) DeleteManualReview(ctx context.Context, in *DeleteManualReviewRequest, opts ...http.CallOption) (*DeleteManualReviewReply, error) {
	var out DeleteManualReviewReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/manual-reviews:delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceDeleteManualReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...http.CallOption) (*DeleteTaskReply, error) {
	var out DeleteTaskReply
	pattern := "/api/v1/squirrel/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) GetReconcileStatus(ctx context.Context, in *GetReconcileStatusRequest, opts ...http.CallOption) (*GetReconcileStatusReply, error) {
	var out GetReconcileStatusReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/reconcile/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceGetReconcileStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) ListManualRemarkOptions(ctx context.Context, in *ListManualRemarkOptionsRequest, opts ...http.CallOption) (*ListManualRemarkOptionsReply, error) {
	var out ListManualRemarkOptionsReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/manual-remark-options"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceListManualRemarkOptions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) ListReconcileRows(ctx context.Context, in *ListReconcileRowsRequest, opts ...http.CallOption) (*ListReconcileRowsReply, error) {
	var out ListReconcileRowsReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/reconcile/rows"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceListReconcileRows))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) ListSectionRows(ctx context.Context, in *ListSectionRowsRequest, opts ...http.CallOption) (*ListSectionRowsReply, error) {
	var out ListSectionRowsReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/sections/{section}/rows"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceListSectionRows))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksReply, error) {
	var out ListTasksReply
	pattern := "/api/v1/squirrel/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSquirrelServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) StartReconcile(ctx context.Context, in *StartReconcileRequest, opts ...http.CallOption) (*StartReconcileReply, error) {
	var out StartReconcileReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/reconcile:start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceStartReconcile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) UploadSectionFile(ctx context.Context, in *UploadSectionFileRequest, opts ...http.CallOption) (*UploadSectionFileReply, error) {
	var out UploadSectionFileReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/sections/{section}/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceUploadSectionFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SquirrelServiceHTTPClientImpl) UpsertManualReview(ctx context.Context, in *UpsertManualReviewRequest, opts ...http.CallOption) (*UpsertManualReviewReply, error) {
	var out UpsertManualReviewReply
	pattern := "/api/v1/squirrel/tasks/{task_id}/manual-reviews:upsert"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSquirrelServiceUpsertManualReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
