// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/squirrel/v1/squirrel.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SquirrelService_ListTasks_FullMethodName                = "/api.squirrel.v1.SquirrelService/ListTasks"
	SquirrelService_CreateTask_FullMethodName               = "/api.squirrel.v1.SquirrelService/CreateTask"
	SquirrelService_DeleteTask_FullMethodName               = "/api.squirrel.v1.SquirrelService/DeleteTask"
	SquirrelService_UploadSectionFile_FullMethodName        = "/api.squirrel.v1.SquirrelService/UploadSectionFile"
	SquirrelService_ListSectionRows_FullMethodName          = "/api.squirrel.v1.SquirrelService/ListSectionRows"
	SquirrelService_ClearSectionData_FullMethodName         = "/api.squirrel.v1.SquirrelService/ClearSectionData"
	SquirrelService_StartReconcile_FullMethodName           = "/api.squirrel.v1.SquirrelService/StartReconcile"
	SquirrelService_GetReconcileStatus_FullMethodName       = "/api.squirrel.v1.SquirrelService/GetReconcileStatus"
	SquirrelService_ListReconcileRows_FullMethodName        = "/api.squirrel.v1.SquirrelService/ListReconcileRows"
	SquirrelService_UpsertManualReview_FullMethodName       = "/api.squirrel.v1.SquirrelService/UpsertManualReview"
	SquirrelService_ClearManualReviews_FullMethodName       = "/api.squirrel.v1.SquirrelService/ClearManualReviews"
	SquirrelService_DeleteManualReview_FullMethodName       = "/api.squirrel.v1.SquirrelService/DeleteManualReview"
	SquirrelService_ListManualRemarkOptions_FullMethodName  = "/api.squirrel.v1.SquirrelService/ListManualRemarkOptions"
	SquirrelService_DeleteManualRemarkOption_FullMethodName = "/api.squirrel.v1.SquirrelService/DeleteManualRemarkOption"
)

// SquirrelServiceClient is the client API for SquirrelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquirrelServiceClient interface {
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskReply, error)
	UploadSectionFile(ctx context.Context, in *UploadSectionFileRequest, opts ...grpc.CallOption) (*UploadSectionFileReply, error)
	ListSectionRows(ctx context.Context, in *ListSectionRowsRequest, opts ...grpc.CallOption) (*ListSectionRowsReply, error)
	ClearSectionData(ctx context.Context, in *ClearSectionDataRequest, opts ...grpc.CallOption) (*ClearSectionDataReply, error)
	StartReconcile(ctx context.Context, in *StartReconcileRequest, opts ...grpc.CallOption) (*StartReconcileReply, error)
	GetReconcileStatus(ctx context.Context, in *GetReconcileStatusRequest, opts ...grpc.CallOption) (*GetReconcileStatusReply, error)
	ListReconcileRows(ctx context.Context, in *ListReconcileRowsRequest, opts ...grpc.CallOption) (*ListReconcileRowsReply, error)
	UpsertManualReview(ctx context.Context, in *UpsertManualReviewRequest, opts ...grpc.CallOption) (*UpsertManualReviewReply, error)
	ClearManualReviews(ctx context.Context, in *ClearManualReviewsRequest, opts ...grpc.CallOption) (*ClearManualReviewsReply, error)
	DeleteManualReview(ctx context.Context, in *DeleteManualReviewRequest, opts ...grpc.CallOption) (*DeleteManualReviewReply, error)
	ListManualRemarkOptions(ctx context.Context, in *ListManualRemarkOptionsRequest, opts ...grpc.CallOption) (*ListManualRemarkOptionsReply, error)
	DeleteManualRemarkOption(ctx context.Context, in *DeleteManualRemarkOptionRequest, opts ...grpc.CallOption) (*DeleteManualRemarkOptionReply, error)
}

type squirrelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSquirrelServiceClient(cc grpc.ClientConnInterface) SquirrelServiceClient {
	return &squirrelServiceClient{cc}
}

func (c *squirrelServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksReply)
	err := c.cc.Invoke(ctx, SquirrelService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskReply)
	err := c.cc.Invoke(ctx, SquirrelService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskReply)
	err := c.cc.Invoke(ctx, SquirrelService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) UploadSectionFile(ctx context.Context, in *UploadSectionFileRequest, opts ...grpc.CallOption) (*UploadSectionFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSectionFileReply)
	err := c.cc.Invoke(ctx, SquirrelService_UploadSectionFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) ListSectionRows(ctx context.Context, in *ListSectionRowsRequest, opts ...grpc.CallOption) (*ListSectionRowsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSectionRowsReply)
	err := c.cc.Invoke(ctx, SquirrelService_ListSectionRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) ClearSectionData(ctx context.Context, in *ClearSectionDataRequest, opts ...grpc.CallOption) (*ClearSectionDataReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSectionDataReply)
	err := c.cc.Invoke(ctx, SquirrelService_ClearSectionData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) StartReconcile(ctx context.Context, in *StartReconcileRequest, opts ...grpc.CallOption) (*StartReconcileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartReconcileReply)
	err := c.cc.Invoke(ctx, SquirrelService_StartReconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) GetReconcileStatus(ctx context.Context, in *GetReconcileStatusRequest, opts ...grpc.CallOption) (*GetReconcileStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReconcileStatusReply)
	err := c.cc.Invoke(ctx, SquirrelService_GetReconcileStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) ListReconcileRows(ctx context.Context, in *ListReconcileRowsRequest, opts ...grpc.CallOption) (*ListReconcileRowsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReconcileRowsReply)
	err := c.cc.Invoke(ctx, SquirrelService_ListReconcileRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) UpsertManualReview(ctx context.Context, in *UpsertManualReviewRequest, opts ...grpc.CallOption) (*UpsertManualReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertManualReviewReply)
	err := c.cc.Invoke(ctx, SquirrelService_UpsertManualReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) ClearManualReviews(ctx context.Context, in *ClearManualReviewsRequest, opts ...grpc.CallOption) (*ClearManualReviewsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearManualReviewsReply)
	err := c.cc.Invoke(ctx, SquirrelService_ClearManualReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) DeleteManualReview(ctx context.Context, in *DeleteManualReviewRequest, opts ...grpc.CallOption) (*DeleteManualReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManualReviewReply)
	err := c.cc.Invoke(ctx, SquirrelService_DeleteManualReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) ListManualRemarkOptions(ctx context.Context, in *ListManualRemarkOptionsRequest, opts ...grpc.CallOption) (*ListManualRemarkOptionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManualRemarkOptionsReply)
	err := c.cc.Invoke(ctx, SquirrelService_ListManualRemarkOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squirrelServiceClient) DeleteManualRemarkOption(ctx context.Context, in *DeleteManualRemarkOptionRequest, opts ...grpc.CallOption) (*DeleteManualRemarkOptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteManualRemarkOptionReply)
	err := c.cc.Invoke(ctx, SquirrelService_DeleteManualRemarkOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquirrelServiceServer is the server API for SquirrelService service.
// All implementations must embed UnimplementedSquirrelServiceServer
// for forward compatibility.
type SquirrelServiceServer interface {
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error)
	UploadSectionFile(context.Context, *UploadSectionFileRequest) (*UploadSectionFileReply, error)
	ListSectionRows(context.Context, *ListSectionRowsRequest) (*ListSectionRowsReply, error)
	ClearSectionData(context.Context, *ClearSectionDataRequest) (*ClearSectionDataReply, error)
	StartReconcile(context.Context, *StartReconcileRequest) (*StartReconcileReply, error)
	GetReconcileStatus(context.Context, *GetReconcileStatusRequest) (*GetReconcileStatusReply, error)
	ListReconcileRows(context.Context, *ListReconcileRowsRequest) (*ListReconcileRowsReply, error)
	UpsertManualReview(context.Context, *UpsertManualReviewRequest) (*UpsertManualReviewReply, error)
	ClearManualReviews(context.Context, *ClearManualReviewsRequest) (*ClearManualReviewsReply, error)
	DeleteManualReview(context.Context, *DeleteManualReviewRequest) (*DeleteManualReviewReply, error)
	ListManualRemarkOptions(context.Context, *ListManualRemarkOptionsRequest) (*ListManualRemarkOptionsReply, error)
	DeleteManualRemarkOption(context.Context, *DeleteManualRemarkOptionRequest) (*DeleteManualRemarkOptionReply, error)
	mustEmbedUnimplementedSquirrelServiceServer()
}

// UnimplementedSquirrelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSquirrelServiceServer struct{}

func (UnimplementedSquirrelServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedSquirrelServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedSquirrelServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedSquirrelServiceServer) UploadSectionFile(context.Context, *UploadSectionFileRequest) (*UploadSectionFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSectionFile not implemented")
}
func (UnimplementedSquirrelServiceServer) ListSectionRows(context.Context, *ListSectionRowsRequest) (*ListSectionRowsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSectionRows not implemented")
}
func (UnimplementedSquirrelServiceServer) ClearSectionData(context.Context, *ClearSectionDataRequest) (*ClearSectionDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSectionData not implemented")
}
func (UnimplementedSquirrelServiceServer) StartReconcile(context.Context, *StartReconcileRequest) (*StartReconcileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartReconcile not implemented")
}
func (UnimplementedSquirrelServiceServer) GetReconcileStatus(context.Context, *GetReconcileStatusRequest) (*GetReconcileStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReconcileStatus not implemented")
}
func (UnimplementedSquirrelServiceServer) ListReconcileRows(context.Context, *ListReconcileRowsRequest) (*ListReconcileRowsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReconcileRows not implemented")
}
func (UnimplementedSquirrelServiceServer) UpsertManualReview(context.Context, *UpsertManualReviewRequest) (*UpsertManualReviewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertManualReview not implemented")
}
func (UnimplementedSquirrelServiceServer) ClearManualReviews(context.Context, *ClearManualReviewsRequest) (*ClearManualReviewsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearManualReviews not implemented")
}
func (UnimplementedSquirrelServiceServer) DeleteManualReview(context.Context, *DeleteManualReviewRequest) (*DeleteManualReviewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManualReview not implemented")
}
func (UnimplementedSquirrelServiceServer) ListManualRemarkOptions(context.Context, *ListManualRemarkOptionsRequest) (*ListManualRemarkOptionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListManualRemarkOptions not implemented")
}
func (UnimplementedSquirrelServiceServer) DeleteManualRemarkOption(context.Context, *DeleteManualRemarkOptionRequest) (*DeleteManualRemarkOptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteManualRemarkOption not implemented")
}
func (UnimplementedSquirrelServiceServer) mustEmbedUnimplementedSquirrelServiceServer() {}
func (UnimplementedSquirrelServiceServer) testEmbeddedByValue()                         {}

// UnsafeSquirrelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquirrelServiceServer will
// result in compilation errors.
type UnsafeSquirrelServiceServer interface {
	mustEmbedUnimplementedSquirrelServiceServer()
}

func RegisterSquirrelServiceServer(s grpc.ServiceRegistrar, srv SquirrelServiceServer) {
	// If the following call pancis, it indicates UnimplementedSquirrelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SquirrelService_ServiceDesc, srv)
}

func _SquirrelService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_UploadSectionFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSectionFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).UploadSectionFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_UploadSectionFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).UploadSectionFile(ctx, req.(*UploadSectionFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_ListSectionRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSectionRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ListSectionRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ListSectionRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ListSectionRows(ctx, req.(*ListSectionRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_ClearSectionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSectionDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ClearSectionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ClearSectionData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ClearSectionData(ctx, req.(*ClearSectionDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_StartReconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).StartReconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_StartReconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).StartReconcile(ctx, req.(*StartReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_GetReconcileStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReconcileStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).GetReconcileStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_GetReconcileStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).GetReconcileStatus(ctx, req.(*GetReconcileStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_ListReconcileRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReconcileRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ListReconcileRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ListReconcileRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ListReconcileRows(ctx, req.(*ListReconcileRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_UpsertManualReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertManualReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).UpsertManualReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_UpsertManualReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).UpsertManualReview(ctx, req.(*UpsertManualReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_ClearManualReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearManualReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ClearManualReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ClearManualReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ClearManualReviews(ctx, req.(*ClearManualReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_DeleteManualReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManualReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).DeleteManualReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_DeleteManualReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).DeleteManualReview(ctx, req.(*DeleteManualReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_ListManualRemarkOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManualRemarkOptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).ListManualRemarkOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_ListManualRemarkOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).ListManualRemarkOptions(ctx, req.(*ListManualRemarkOptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquirrelService_DeleteManualRemarkOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteManualRemarkOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquirrelServiceServer).DeleteManualRemarkOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquirrelService_DeleteManualRemarkOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquirrelServiceServer).DeleteManualRemarkOption(ctx, req.(*DeleteManualRemarkOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquirrelService_ServiceDesc is the grpc.ServiceDesc for SquirrelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquirrelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.squirrel.v1.SquirrelService",
	HandlerType: (*SquirrelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _SquirrelService_ListTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _SquirrelService_CreateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _SquirrelService_DeleteTask_Handler,
		},
		{
			MethodName: "UploadSectionFile",
			Handler:    _SquirrelService_UploadSectionFile_Handler,
		},
		{
			MethodName: "ListSectionRows",
			Handler:    _SquirrelService_ListSectionRows_Handler,
		},
		{
			MethodName: "ClearSectionData",
			Handler:    _SquirrelService_ClearSectionData_Handler,
		},
		{
			MethodName: "StartReconcile",
			Handler:    _SquirrelService_StartReconcile_Handler,
		},
		{
			MethodName: "GetReconcileStatus",
			Handler:    _SquirrelService_GetReconcileStatus_Handler,
		},
		{
			MethodName: "ListReconcileRows",
			Handler:    _SquirrelService_ListReconcileRows_Handler,
		},
		{
			MethodName: "UpsertManualReview",
			Handler:    _SquirrelService_UpsertManualReview_Handler,
		},
		{
			MethodName: "ClearManualReviews",
			Handler:    _SquirrelService_ClearManualReviews_Handler,
		},
		{
			MethodName: "DeleteManualReview",
			Handler:    _SquirrelService_DeleteManualReview_Handler,
		},
		{
			MethodName: "ListManualRemarkOptions",
			Handler:    _SquirrelService_ListManualRemarkOptions_Handler,
		},
		{
			MethodName: "DeleteManualRemarkOption",
			Handler:    _SquirrelService_DeleteManualRemarkOption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/squirrel/v1/squirrel.proto",
}
