// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/squirrel/v1/squirrel.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{0}
}

type ListTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Task                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReply) Reset() {
	*x = ListTasksReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReply) ProtoMessage() {}

func (x *ListTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReply.ProtoReflect.Descriptor instead.
func (*ListTasksReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksReply) GetItems() []*Task {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MonthTag      string                 `protobuf:"bytes,2,opt,name=month_tag,json=monthTag,proto3" json:"month_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetMonthTag() string {
	if x != nil {
		return x.MonthTag
	}
	return ""
}

type CreateTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Task                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskReply) Reset() {
	*x = CreateTaskReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReply) ProtoMessage() {}

func (x *CreateTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReply.ProtoReflect.Descriptor instead.
func (*CreateTaskReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskReply) GetItem() *Task {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskReply) Reset() {
	*x = DeleteTaskReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskReply) ProtoMessage() {}

func (x *DeleteTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskReply.ProtoReflect.Descriptor instead.
func (*DeleteTaskReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTaskReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadSectionFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,4,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSectionFileRequest) Reset() {
	*x = UploadSectionFileRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSectionFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSectionFileRequest) ProtoMessage() {}

func (x *UploadSectionFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSectionFileRequest.ProtoReflect.Descriptor instead.
func (*UploadSectionFileRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{6}
}

func (x *UploadSectionFileRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UploadSectionFileRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *UploadSectionFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadSectionFileRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type UploadSectionFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *SectionSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSectionFileReply) Reset() {
	*x = UploadSectionFileReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSectionFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSectionFileReply) ProtoMessage() {}

func (x *UploadSectionFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSectionFileReply.ProtoReflect.Descriptor instead.
func (*UploadSectionFileReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{7}
}

func (x *UploadSectionFileReply) GetSummary() *SectionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type ListSectionRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSectionRowsRequest) Reset() {
	*x = ListSectionRowsRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSectionRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSectionRowsRequest) ProtoMessage() {}

func (x *ListSectionRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSectionRowsRequest.ProtoReflect.Descriptor instead.
func (*ListSectionRowsRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{8}
}

func (x *ListSectionRowsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListSectionRowsRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ListSectionRowsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSectionRowsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSectionRowsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *SectionSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*SheetRow            `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	Page          uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         uint32                 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Summaries     []*SectionSummary      `protobuf:"bytes,7,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSectionRowsReply) Reset() {
	*x = ListSectionRowsReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSectionRowsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSectionRowsReply) ProtoMessage() {}

func (x *ListSectionRowsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSectionRowsReply.ProtoReflect.Descriptor instead.
func (*ListSectionRowsReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{9}
}

func (x *ListSectionRowsReply) GetSummary() *SectionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ListSectionRowsReply) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ListSectionRowsReply) GetRows() []*SheetRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListSectionRowsReply) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSectionRowsReply) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSectionRowsReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSectionRowsReply) GetSummaries() []*SectionSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type ClearSectionDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSectionDataRequest) Reset() {
	*x = ClearSectionDataRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSectionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSectionDataRequest) ProtoMessage() {}

func (x *ClearSectionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSectionDataRequest.ProtoReflect.Descriptor instead.
func (*ClearSectionDataRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{10}
}

func (x *ClearSectionDataRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ClearSectionDataRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ClearSectionDataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ClearSectionDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearSectionDataReply) Reset() {
	*x = ClearSectionDataReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSectionDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSectionDataReply) ProtoMessage() {}

func (x *ClearSectionDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSectionDataReply.ProtoReflect.Descriptor instead.
func (*ClearSectionDataReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{11}
}

func (x *ClearSectionDataReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReconcileRequest) Reset() {
	*x = StartReconcileRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReconcileRequest) ProtoMessage() {}

func (x *StartReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReconcileRequest.ProtoReflect.Descriptor instead.
func (*StartReconcileRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{12}
}

func (x *StartReconcileRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartReconcileRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StartReconcileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ReconcileRun          `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReconcileReply) Reset() {
	*x = StartReconcileReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReconcileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReconcileReply) ProtoMessage() {}

func (x *StartReconcileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReconcileReply.ProtoReflect.Descriptor instead.
func (*StartReconcileReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{13}
}

func (x *StartReconcileReply) GetRun() *ReconcileRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type GetReconcileStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconcileStatusRequest) Reset() {
	*x = GetReconcileStatusRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcileStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcileStatusRequest) ProtoMessage() {}

func (x *GetReconcileStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconcileStatusRequest.ProtoReflect.Descriptor instead.
func (*GetReconcileStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{14}
}

func (x *GetReconcileStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetReconcileStatusRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetReconcileStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ReconcileRun          `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconcileStatusReply) Reset() {
	*x = GetReconcileStatusReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconcileStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconcileStatusReply) ProtoMessage() {}

func (x *GetReconcileStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconcileStatusReply.ProtoReflect.Descriptor instead.
func (*GetReconcileStatusReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{15}
}

func (x *GetReconcileStatusReply) GetRun() *ReconcileRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListReconcileRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileRowsRequest) Reset() {
	*x = ListReconcileRowsRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileRowsRequest) ProtoMessage() {}

func (x *ListReconcileRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileRowsRequest.ProtoReflect.Descriptor instead.
func (*ListReconcileRowsRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{16}
}

func (x *ListReconcileRowsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListReconcileRowsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListReconcileRowsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReconcileRowsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReconcileRowsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *ReconcileRun          `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*ReconcileRow        `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	Page          uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         uint32                 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconcileRowsReply) Reset() {
	*x = ListReconcileRowsReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconcileRowsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconcileRowsReply) ProtoMessage() {}

func (x *ListReconcileRowsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconcileRowsReply.ProtoReflect.Descriptor instead.
func (*ListReconcileRowsReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{17}
}

func (x *ListReconcileRowsReply) GetRun() *ReconcileRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *ListReconcileRowsReply) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ListReconcileRowsReply) GetRows() []*ReconcileRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListReconcileRowsReply) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReconcileRowsReply) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReconcileRowsReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpsertManualReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	RowNo         uint32                 `protobuf:"varint,3,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`
	RefundQty     string                 `protobuf:"bytes,4,opt,name=refund_qty,json=refundQty,proto3" json:"refund_qty,omitempty"`
	RefundAmount  string                 `protobuf:"bytes,5,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	Ignored       bool                   `protobuf:"varint,6,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertManualReviewRequest) Reset() {
	*x = UpsertManualReviewRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertManualReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertManualReviewRequest) ProtoMessage() {}

func (x *UpsertManualReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertManualReviewRequest.ProtoReflect.Descriptor instead.
func (*UpsertManualReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{18}
}

func (x *UpsertManualReviewRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpsertManualReviewRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpsertManualReviewRequest) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *UpsertManualReviewRequest) GetRefundQty() string {
	if x != nil {
		return x.RefundQty
	}
	return ""
}

func (x *UpsertManualReviewRequest) GetRefundAmount() string {
	if x != nil {
		return x.RefundAmount
	}
	return ""
}

func (x *UpsertManualReviewRequest) GetIgnored() bool {
	if x != nil {
		return x.Ignored
	}
	return false
}

func (x *UpsertManualReviewRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpsertManualReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *ManualReview          `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertManualReviewReply) Reset() {
	*x = UpsertManualReviewReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertManualReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertManualReviewReply) ProtoMessage() {}

func (x *UpsertManualReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertManualReviewReply.ProtoReflect.Descriptor instead.
func (*UpsertManualReviewReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{19}
}

func (x *UpsertManualReviewReply) GetReview() *ManualReview {
	if x != nil {
		return x.Review
	}
	return nil
}

type ClearManualReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearManualReviewsRequest) Reset() {
	*x = ClearManualReviewsRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearManualReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearManualReviewsRequest) ProtoMessage() {}

func (x *ClearManualReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearManualReviewsRequest.ProtoReflect.Descriptor instead.
func (*ClearManualReviewsRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{20}
}

func (x *ClearManualReviewsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ClearManualReviewsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearManualReviewsReply) Reset() {
	*x = ClearManualReviewsReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearManualReviewsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearManualReviewsReply) ProtoMessage() {}

func (x *ClearManualReviewsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearManualReviewsReply.ProtoReflect.Descriptor instead.
func (*ClearManualReviewsReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{21}
}

func (x *ClearManualReviewsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListManualRemarkOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManualRemarkOptionsRequest) Reset() {
	*x = ListManualRemarkOptionsRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManualRemarkOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManualRemarkOptionsRequest) ProtoMessage() {}

func (x *ListManualRemarkOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManualRemarkOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListManualRemarkOptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{22}
}

func (x *ListManualRemarkOptionsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListManualRemarkOptionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ManualRemarkOption  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManualRemarkOptionsReply) Reset() {
	*x = ListManualRemarkOptionsReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManualRemarkOptionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManualRemarkOptionsReply) ProtoMessage() {}

func (x *ListManualRemarkOptionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManualRemarkOptionsReply.ProtoReflect.Descriptor instead.
func (*ListManualRemarkOptionsReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{23}
}

func (x *ListManualRemarkOptionsReply) GetItems() []*ManualRemarkOption {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteManualRemarkOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManualRemarkOptionRequest) Reset() {
	*x = DeleteManualRemarkOptionRequest{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManualRemarkOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManualRemarkOptionRequest) ProtoMessage() {}

func (x *DeleteManualRemarkOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManualRemarkOptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteManualRemarkOptionRequest) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteManualRemarkOptionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeleteManualRemarkOptionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeleteManualRemarkOptionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManualRemarkOptionReply) Reset() {
	*x = DeleteManualRemarkOptionReply{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManualRemarkOptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManualRemarkOptionReply) ProtoMessage() {}

func (x *DeleteManualRemarkOptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManualRemarkOptionReply.ProtoReflect.Descriptor instead.
func (*DeleteManualRemarkOptionReply) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteManualRemarkOptionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MonthTag         string                 `protobuf:"bytes,3,opt,name=month_tag,json=monthTag,proto3" json:"month_tag,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SectionSummaries []*SectionSummary      `protobuf:"bytes,6,rep,name=section_summaries,json=sectionSummaries,proto3" json:"section_summaries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{26}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetMonthTag() string {
	if x != nil {
		return x.MonthTag
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Task) GetSectionSummaries() []*SectionSummary {
	if x != nil {
		return x.SectionSummaries
	}
	return nil
}

type SectionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	SheetName     string                 `protobuf:"bytes,4,opt,name=sheet_name,json=sheetName,proto3" json:"sheet_name,omitempty"`
	TotalRows     uint32                 `protobuf:"varint,5,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	ColumnCount   uint32                 `protobuf:"varint,6,opt,name=column_count,json=columnCount,proto3" json:"column_count,omitempty"`
	Header        []string               `protobuf:"bytes,7,rep,name=header,proto3" json:"header,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionSummary) Reset() {
	*x = SectionSummary{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionSummary) ProtoMessage() {}

func (x *SectionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionSummary.ProtoReflect.Descriptor instead.
func (*SectionSummary) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{27}
}

func (x *SectionSummary) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SectionSummary) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *SectionSummary) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SectionSummary) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

func (x *SectionSummary) GetTotalRows() uint32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *SectionSummary) GetColumnCount() uint32 {
	if x != nil {
		return x.ColumnCount
	}
	return 0
}

func (x *SectionSummary) GetHeader() []string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SectionSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNo         uint32                 `protobuf:"varint,1,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SheetRow) Reset() {
	*x = SheetRow{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetRow) ProtoMessage() {}

func (x *SheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetRow.ProtoReflect.Descriptor instead.
func (*SheetRow) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{28}
}

func (x *SheetRow) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *SheetRow) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SheetRow) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ReconcileRun struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskId          string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Progress        uint32                 `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Stage           string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Reused          bool                   `protobuf:"varint,7,opt,name=reused,proto3" json:"reused,omitempty"`
	DataFingerprint string                 `protobuf:"bytes,8,opt,name=data_fingerprint,json=dataFingerprint,proto3" json:"data_fingerprint,omitempty"`
	TotalRows       uint32                 `protobuf:"varint,9,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	ProcessedRows   uint32                 `protobuf:"varint,10,opt,name=processed_rows,json=processedRows,proto3" json:"processed_rows,omitempty"`
	MatchedRows     uint32                 `protobuf:"varint,11,opt,name=matched_rows,json=matchedRows,proto3" json:"matched_rows,omitempty"`
	ResultTotalRows uint32                 `protobuf:"varint,12,opt,name=result_total_rows,json=resultTotalRows,proto3" json:"result_total_rows,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FinishedAt      string                 `protobuf:"bytes,15,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReconcileRun) Reset() {
	*x = ReconcileRun{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRun) ProtoMessage() {}

func (x *ReconcileRun) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRun.ProtoReflect.Descriptor instead.
func (*ReconcileRun) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{29}
}

func (x *ReconcileRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReconcileRun) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReconcileRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconcileRun) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ReconcileRun) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ReconcileRun) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReconcileRun) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

func (x *ReconcileRun) GetDataFingerprint() string {
	if x != nil {
		return x.DataFingerprint
	}
	return ""
}

func (x *ReconcileRun) GetTotalRows() uint32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ReconcileRun) GetProcessedRows() uint32 {
	if x != nil {
		return x.ProcessedRows
	}
	return 0
}

func (x *ReconcileRun) GetMatchedRows() uint32 {
	if x != nil {
		return x.MatchedRows
	}
	return 0
}

func (x *ReconcileRun) GetResultTotalRows() uint32 {
	if x != nil {
		return x.ResultTotalRows
	}
	return 0
}

func (x *ReconcileRun) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReconcileRun) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ReconcileRun) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

type ReconcileRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNo         uint32                 `protobuf:"varint,1,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Matches       []*ReconcileMatch      `protobuf:"bytes,3,rep,name=matches,proto3" json:"matches,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ManualReview  *ManualReview          `protobuf:"bytes,5,opt,name=manual_review,json=manualReview,proto3" json:"manual_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRow) Reset() {
	*x = ReconcileRow{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRow) ProtoMessage() {}

func (x *ReconcileRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRow.ProtoReflect.Descriptor instead.
func (*ReconcileRow) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{30}
}

func (x *ReconcileRow) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *ReconcileRow) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ReconcileRow) GetMatches() []*ReconcileMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *ReconcileRow) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReconcileRow) GetManualReview() *ManualReview {
	if x != nil {
		return x.ManualReview
	}
	return nil
}

type ReconcileMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	RowNo         uint32                 `protobuf:"varint,2,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`
	Detail        []*KeyValue            `protobuf:"bytes,3,rep,name=detail,proto3" json:"detail,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileMatch) Reset() {
	*x = ReconcileMatch{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileMatch) ProtoMessage() {}

func (x *ReconcileMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileMatch.ProtoReflect.Descriptor instead.
func (*ReconcileMatch) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{31}
}

func (x *ReconcileMatch) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReconcileMatch) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *ReconcileMatch) GetDetail() []*KeyValue {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ReconcileMatch) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ManualReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	RowNo         uint32                 `protobuf:"varint,3,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`
	RefundQty     string                 `protobuf:"bytes,4,opt,name=refund_qty,json=refundQty,proto3" json:"refund_qty,omitempty"`
	RefundAmount  string                 `protobuf:"bytes,5,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	SettleQty     string                 `protobuf:"bytes,6,opt,name=settle_qty,json=settleQty,proto3" json:"settle_qty,omitempty"`
	SettleAmount  string                 `protobuf:"bytes,7,opt,name=settle_amount,json=settleAmount,proto3" json:"settle_amount,omitempty"`
	Ignored       bool                   `protobuf:"varint,8,opt,name=ignored,proto3" json:"ignored,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ReviewType    string                 `protobuf:"bytes,10,opt,name=review_type,json=reviewType,proto3" json:"review_type,omitempty"`
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualReview) Reset() {
	*x = ManualReview{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualReview) ProtoMessage() {}

func (x *ManualReview) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualReview.ProtoReflect.Descriptor instead.
func (*ManualReview) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{32}
}

func (x *ManualReview) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ManualReview) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ManualReview) GetRowNo() uint32 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *ManualReview) GetRefundQty() string {
	if x != nil {
		return x.RefundQty
	}
	return ""
}

func (x *ManualReview) GetRefundAmount() string {
	if x != nil {
		return x.RefundAmount
	}
	return ""
}

func (x *ManualReview) GetSettleQty() string {
	if x != nil {
		return x.SettleQty
	}
	return ""
}

func (x *ManualReview) GetSettleAmount() string {
	if x != nil {
		return x.SettleAmount
	}
	return ""
}

func (x *ManualReview) GetIgnored() bool {
	if x != nil {
		return x.Ignored
	}
	return false
}

func (x *ManualReview) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ManualReview) GetReviewType() string {
	if x != nil {
		return x.ReviewType
	}
	return ""
}

func (x *ManualReview) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ManualRemarkOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UsedCount     uint32                 `protobuf:"varint,3,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualRemarkOption) Reset() {
	*x = ManualRemarkOption{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualRemarkOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualRemarkOption) ProtoMessage() {}

func (x *ManualRemarkOption) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualRemarkOption.ProtoReflect.Descriptor instead.
func (*ManualRemarkOption) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{33}
}

func (x *ManualRemarkOption) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ManualRemarkOption) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ManualRemarkOption) GetUsedCount() uint32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *ManualRemarkOption) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_squirrel_v1_squirrel_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_api_squirrel_v1_squirrel_proto_rawDescGZIP(), []int{34}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_squirrel_v1_squirrel_proto protoreflect.FileDescriptor

const file_api_squirrel_v1_squirrel_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/squirrel/v1/squirrel.proto\x12\x0fapi.squirrel.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10ListTasksRequest\"=\n" +
	"\x0eListTasksReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.api.squirrel.v1.TaskR\x05items\"F\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1b\n" +
	"\tmonth_tag\x18\x02 \x01(\tR\bmonthTag\"<\n" +
	"\x0fCreateTaskReply\x12)\n" +
	"\x04item\x18\x01 \x01(\v2\x15.api.squirrel.v1.TaskR\x04item\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x0fDeleteTaskReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\x18UploadSectionFileRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12!\n" +
	"\ffile_content\x18\x04 \x01(\fR\vfileContent\"S\n" +
	"\x16UploadSectionFileReply\x129\n" +
	"\asummary\x18\x01 \x01(\v2\x1f.api.squirrel.v1.SectionSummaryR\asummary\"|\n" +
	"\x16ListSectionRowsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\xa0\x02\n" +
	"\x14ListSectionRowsReply\x129\n" +
	"\asummary\x18\x01 \x01(\v2\x1f.api.squirrel.v1.SectionSummaryR\asummary\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12-\n" +
	"\x04rows\x18\x03 \x03(\v2\x19.api.squirrel.v1.SheetRowR\x04rows\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\rR\bpageSize\x12\x14\n" +
	"\x05total\x18\x06 \x01(\rR\x05total\x12=\n" +
	"\tsummaries\x18\a \x03(\v2\x1f.api.squirrel.v1.SectionSummaryR\tsummaries\"h\n" +
	"\x17ClearSectionDataRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"1\n" +
	"\x15ClearSectionDataReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x15StartReconcileRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"F\n" +
	"\x13StartReconcileReply\x12/\n" +
	"\x03run\x18\x01 \x01(\v2\x1d.api.squirrel.v1.ReconcileRunR\x03run\"K\n" +
	"\x19GetReconcileStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"J\n" +
	"\x17GetReconcileStatusReply\x12/\n" +
	"\x03run\x18\x01 \x01(\v2\x1d.api.squirrel.v1.ReconcileRunR\x03run\"{\n" +
	"\x18ListReconcileRowsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\xdd\x01\n" +
	"\x16ListReconcileRowsReply\x12/\n" +
	"\x03run\x18\x01 \x01(\v2\x1d.api.squirrel.v1.ReconcileRunR\x03run\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x121\n" +
	"\x04rows\x18\x03 \x03(\v2\x1d.api.squirrel.v1.ReconcileRowR\x04rows\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\rR\bpageSize\x12\x14\n" +
	"\x05total\x18\x06 \x01(\rR\x05total\"\xdd\x01\n" +
	"\x19UpsertManualReviewRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x15\n" +
	"\x06row_no\x18\x03 \x01(\rR\x05rowNo\x12\x1d\n" +
	"\n" +
	"refund_qty\x18\x04 \x01(\tR\trefundQty\x12#\n" +
	"\rrefund_amount\x18\x05 \x01(\tR\frefundAmount\x12\x18\n" +
	"\aignored\x18\x06 \x01(\bR\aignored\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\"P\n" +
	"\x17UpsertManualReviewReply\x125\n" +
	"\x06review\x18\x01 \x01(\v2\x1d.api.squirrel.v1.ManualReviewR\x06review\"4\n" +
	"\x19ClearManualReviewsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"3\n" +
	"\x17ClearManualReviewsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"9\n" +
	"\x1eListManualRemarkOptionsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"Y\n" +
	"\x1cListManualRemarkOptionsReply\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.api.squirrel.v1.ManualRemarkOptionR\x05items\"T\n" +
	"\x1fDeleteManualRemarkOptionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"9\n" +
	"\x1dDeleteManualRemarkOptionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xde\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tmonth_tag\x18\x03 \x01(\tR\bmonthTag\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12L\n" +
	"\x11section_summaries\x18\x06 \x03(\v2\x1f.api.squirrel.v1.SectionSummaryR\x10sectionSummaries\"\xf7\x01\n" +
	"\x0eSectionSummary\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"sheet_name\x18\x04 \x01(\tR\tsheetName\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x05 \x01(\rR\ttotalRows\x12!\n" +
	"\fcolumn_count\x18\x06 \x01(\rR\vcolumnCount\x12\x16\n" +
	"\x06header\x18\a \x03(\tR\x06header\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"U\n" +
	"\bSheetRow\x12\x15\n" +
	"\x06row_no\x18\x01 \x01(\rR\x05rowNo\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"\xd9\x03\n" +
	"\fReconcileRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\rR\bprogress\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x16\n" +
	"\x06reused\x18\a \x01(\bR\x06reused\x12)\n" +
	"\x10data_fingerprint\x18\b \x01(\tR\x0fdataFingerprint\x12\x1d\n" +
	"\n" +
	"total_rows\x18\t \x01(\rR\ttotalRows\x12%\n" +
	"\x0eprocessed_rows\x18\n" +
	" \x01(\rR\rprocessedRows\x12!\n" +
	"\fmatched_rows\x18\v \x01(\rR\vmatchedRows\x12*\n" +
	"\x11result_total_rows\x18\f \x01(\rR\x0fresultTotalRows\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vfinished_at\x18\x0f \x01(\tR\n" +
	"finishedAt\"\xd8\x01\n" +
	"\fReconcileRow\x12\x15\n" +
	"\x06row_no\x18\x01 \x01(\rR\x05rowNo\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x129\n" +
	"\amatches\x18\x03 \x03(\v2\x1f.api.squirrel.v1.ReconcileMatchR\amatches\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12B\n" +
	"\rmanual_review\x18\x05 \x01(\v2\x1d.api.squirrel.v1.ManualReviewR\fmanualReview\"\x8e\x01\n" +
	"\x0eReconcileMatch\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x15\n" +
	"\x06row_no\x18\x02 \x01(\rR\x05rowNo\x121\n" +
	"\x06detail\x18\x03 \x03(\v2\x19.api.squirrel.v1.KeyValueR\x06detail\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\"\xd4\x02\n" +
	"\fManualReview\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x15\n" +
	"\x06row_no\x18\x03 \x01(\rR\x05rowNo\x12\x1d\n" +
	"\n" +
	"refund_qty\x18\x04 \x01(\tR\trefundQty\x12#\n" +
	"\rrefund_amount\x18\x05 \x01(\tR\frefundAmount\x12\x1d\n" +
	"\n" +
	"settle_qty\x18\x06 \x01(\tR\tsettleQty\x12#\n" +
	"\rsettle_amount\x18\a \x01(\tR\fsettleAmount\x12\x18\n" +
	"\aignored\x18\b \x01(\bR\aignored\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\vreview_type\x18\n" +
	" \x01(\tR\n" +
	"reviewType\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\"\x85\x01\n" +
	"\x12ManualRemarkOption\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"used_count\x18\x03 \x01(\rR\tusedCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xbb\x10\n" +
	"\x0fSquirrelService\x12o\n" +
	"\tListTasks\x12!.api.squirrel.v1.ListTasksRequest\x1a\x1f.api.squirrel.v1.ListTasksReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/squirrel/tasks\x12u\n" +
	"\n" +
	"CreateTask\x12\".api.squirrel.v1.CreateTaskRequest\x1a .api.squirrel.v1.CreateTaskReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/squirrel/tasks\x12|\n" +
	"\n" +
	"DeleteTask\x12\".api.squirrel.v1.DeleteTaskRequest\x1a .api.squirrel.v1.DeleteTaskReply\"(\x82\xd3\xe4\x93\x02\"* /api/v1/squirrel/tasks/{task_id}\x12\xae\x01\n" +
	"\x11UploadSectionFile\x12).api.squirrel.v1.UploadSectionFileRequest\x1a'.api.squirrel.v1.UploadSectionFileReply\"E\x82\xd3\xe4\x93\x02?:\x01*\":/api/v1/squirrel/tasks/{task_id}/sections/{section}/upload\x12\xa3\x01\n" +
	"\x0fListSectionRows\x12'.api.squirrel.v1.ListSectionRowsRequest\x1a%.api.squirrel.v1.ListSectionRowsReply\"@\x82\xd3\xe4\x93\x02:\x128/api/v1/squirrel/tasks/{task_id}/sections/{section}/rows\x12\xa6\x01\n" +
	"\x10ClearSectionData\x12(.api.squirrel.v1.ClearSectionDataRequest\x1a&.api.squirrel.v1.ClearSectionDataReply\"@\x82\xd3\xe4\x93\x02:*8/api/v1/squirrel/tasks/{task_id}/sections/{section}/data\x12\x9b\x01\n" +
	"\x0eStartReconcile\x12&.api.squirrel.v1.StartReconcileRequest\x1a$.api.squirrel.v1.StartReconcileReply\";\x82\xd3\xe4\x93\x025:\x01*\"0/api/v1/squirrel/tasks/{task_id}/reconcile:start\x12\xa5\x01\n" +
	"\x12GetReconcileStatus\x12*.api.squirrel.v1.GetReconcileStatusRequest\x1a(.api.squirrel.v1.GetReconcileStatusReply\"9\x82\xd3\xe4\x93\x023\x121/api/v1/squirrel/tasks/{task_id}/reconcile/status\x12\xa0\x01\n" +
	"\x11ListReconcileRows\x12).api.squirrel.v1.ListReconcileRowsRequest\x1a'.api.squirrel.v1.ListReconcileRowsReply\"7\x82\xd3\xe4\x93\x021\x12//api/v1/squirrel/tasks/{task_id}/reconcile/rows\x12\xad\x01\n" +
	"\x12UpsertManualReview\x12*.api.squirrel.v1.UpsertManualReviewRequest\x1a(.api.squirrel.v1.UpsertManualReviewReply\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/api/v1/squirrel/tasks/{task_id}/manual-reviews:upsert\x12\xa3\x01\n" +
	"\x12ClearManualReviews\x12*.api.squirrel.v1.ClearManualReviewsRequest\x1a(.api.squirrel.v1.ClearManualReviewsReply\"7\x82\xd3\xe4\x93\x021*//api/v1/squirrel/tasks/{task_id}/manual-reviews\x12\xb9\x01\n" +
	"\x17ListManualRemarkOptions\x12/.api.squirrel.v1.ListManualRemarkOptionsRequest\x1a-.api.squirrel.v1.ListManualRemarkOptionsReply\">\x82\xd3\xe4\x93\x028\x126/api/v1/squirrel/tasks/{task_id}/manual-remark-options\x12\xc6\x01\n" +
	"\x18DeleteManualRemarkOption\x120.api.squirrel.v1.DeleteManualRemarkOptionRequest\x1a..api.squirrel.v1.DeleteManualRemarkOptionReply\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/api/v1/squirrel/tasks/{task_id}/manual-remark-options:deleteB\xb4\x01\n" +
	"\x13com.api.squirrel.v1B\rSquirrelProtoP\x01Z0github.com/jeffinity/oculus/proto/squirrel/v1;v1\xa2\x02\x03ASX\xaa\x02\x0fApi.Squirrel.V1\xca\x02\x0fApi\\Squirrel\\V1\xe2\x02\x1bApi\\Squirrel\\V1\\GPBMetadata\xea\x02\x11Api::Squirrel::V1b\x06proto3"

var (
	file_api_squirrel_v1_squirrel_proto_rawDescOnce sync.Once
	file_api_squirrel_v1_squirrel_proto_rawDescData []byte
)

func file_api_squirrel_v1_squirrel_proto_rawDescGZIP() []byte {
	file_api_squirrel_v1_squirrel_proto_rawDescOnce.Do(func() {
		file_api_squirrel_v1_squirrel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_squirrel_v1_squirrel_proto_rawDesc), len(file_api_squirrel_v1_squirrel_proto_rawDesc)))
	})
	return file_api_squirrel_v1_squirrel_proto_rawDescData
}

var file_api_squirrel_v1_squirrel_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_squirrel_v1_squirrel_proto_goTypes = []any{
	(*ListTasksRequest)(nil),                // 0: api.squirrel.v1.ListTasksRequest
	(*ListTasksReply)(nil),                  // 1: api.squirrel.v1.ListTasksReply
	(*CreateTaskRequest)(nil),               // 2: api.squirrel.v1.CreateTaskRequest
	(*CreateTaskReply)(nil),                 // 3: api.squirrel.v1.CreateTaskReply
	(*DeleteTaskRequest)(nil),               // 4: api.squirrel.v1.DeleteTaskRequest
	(*DeleteTaskReply)(nil),                 // 5: api.squirrel.v1.DeleteTaskReply
	(*UploadSectionFileRequest)(nil),        // 6: api.squirrel.v1.UploadSectionFileRequest
	(*UploadSectionFileReply)(nil),          // 7: api.squirrel.v1.UploadSectionFileReply
	(*ListSectionRowsRequest)(nil),          // 8: api.squirrel.v1.ListSectionRowsRequest
	(*ListSectionRowsReply)(nil),            // 9: api.squirrel.v1.ListSectionRowsReply
	(*ClearSectionDataRequest)(nil),         // 10: api.squirrel.v1.ClearSectionDataRequest
	(*ClearSectionDataReply)(nil),           // 11: api.squirrel.v1.ClearSectionDataReply
	(*StartReconcileRequest)(nil),           // 12: api.squirrel.v1.StartReconcileRequest
	(*StartReconcileReply)(nil),             // 13: api.squirrel.v1.StartReconcileReply
	(*GetReconcileStatusRequest)(nil),       // 14: api.squirrel.v1.GetReconcileStatusRequest
	(*GetReconcileStatusReply)(nil),         // 15: api.squirrel.v1.GetReconcileStatusReply
	(*ListReconcileRowsRequest)(nil),        // 16: api.squirrel.v1.ListReconcileRowsRequest
	(*ListReconcileRowsReply)(nil),          // 17: api.squirrel.v1.ListReconcileRowsReply
	(*UpsertManualReviewRequest)(nil),       // 18: api.squirrel.v1.UpsertManualReviewRequest
	(*UpsertManualReviewReply)(nil),         // 19: api.squirrel.v1.UpsertManualReviewReply
	(*ClearManualReviewsRequest)(nil),       // 20: api.squirrel.v1.ClearManualReviewsRequest
	(*ClearManualReviewsReply)(nil),         // 21: api.squirrel.v1.ClearManualReviewsReply
	(*ListManualRemarkOptionsRequest)(nil),  // 22: api.squirrel.v1.ListManualRemarkOptionsRequest
	(*ListManualRemarkOptionsReply)(nil),    // 23: api.squirrel.v1.ListManualRemarkOptionsReply
	(*DeleteManualRemarkOptionRequest)(nil), // 24: api.squirrel.v1.DeleteManualRemarkOptionRequest
	(*DeleteManualRemarkOptionReply)(nil),   // 25: api.squirrel.v1.DeleteManualRemarkOptionReply
	(*Task)(nil),                            // 26: api.squirrel.v1.Task
	(*SectionSummary)(nil),                  // 27: api.squirrel.v1.SectionSummary
	(*SheetRow)(nil),                        // 28: api.squirrel.v1.SheetRow
	(*ReconcileRun)(nil),                    // 29: api.squirrel.v1.ReconcileRun
	(*ReconcileRow)(nil),                    // 30: api.squirrel.v1.ReconcileRow
	(*ReconcileMatch)(nil),                  // 31: api.squirrel.v1.ReconcileMatch
	(*ManualReview)(nil),                    // 32: api.squirrel.v1.ManualReview
	(*ManualRemarkOption)(nil),              // 33: api.squirrel.v1.ManualRemarkOption
	(*KeyValue)(nil),                        // 34: api.squirrel.v1.KeyValue
}
var file_api_squirrel_v1_squirrel_proto_depIdxs = []int32{
	26, // 0: api.squirrel.v1.ListTasksReply.items:type_name -> api.squirrel.v1.Task
	26, // 1: api.squirrel.v1.CreateTaskReply.item:type_name -> api.squirrel.v1.Task
	27, // 2: api.squirrel.v1.UploadSectionFileReply.summary:type_name -> api.squirrel.v1.SectionSummary
	27, // 3: api.squirrel.v1.ListSectionRowsReply.summary:type_name -> api.squirrel.v1.SectionSummary
	28, // 4: api.squirrel.v1.ListSectionRowsReply.rows:type_name -> api.squirrel.v1.SheetRow
	27, // 5: api.squirrel.v1.ListSectionRowsReply.summaries:type_name -> api.squirrel.v1.SectionSummary
	29, // 6: api.squirrel.v1.StartReconcileReply.run:type_name -> api.squirrel.v1.ReconcileRun
	29, // 7: api.squirrel.v1.GetReconcileStatusReply.run:type_name -> api.squirrel.v1.ReconcileRun
	29, // 8: api.squirrel.v1.ListReconcileRowsReply.run:type_name -> api.squirrel.v1.ReconcileRun
	30, // 9: api.squirrel.v1.ListReconcileRowsReply.rows:type_name -> api.squirrel.v1.ReconcileRow
	32, // 10: api.squirrel.v1.UpsertManualReviewReply.review:type_name -> api.squirrel.v1.ManualReview
	33, // 11: api.squirrel.v1.ListManualRemarkOptionsReply.items:type_name -> api.squirrel.v1.ManualRemarkOption
	27, // 12: api.squirrel.v1.Task.section_summaries:type_name -> api.squirrel.v1.SectionSummary
	31, // 13: api.squirrel.v1.ReconcileRow.matches:type_name -> api.squirrel.v1.ReconcileMatch
	32, // 14: api.squirrel.v1.ReconcileRow.manual_review:type_name -> api.squirrel.v1.ManualReview
	34, // 15: api.squirrel.v1.ReconcileMatch.detail:type_name -> api.squirrel.v1.KeyValue
	0,  // 16: api.squirrel.v1.SquirrelService.ListTasks:input_type -> api.squirrel.v1.ListTasksRequest
	2,  // 17: api.squirrel.v1.SquirrelService.CreateTask:input_type -> api.squirrel.v1.CreateTaskRequest
	4,  // 18: api.squirrel.v1.SquirrelService.DeleteTask:input_type -> api.squirrel.v1.DeleteTaskRequest
	6,  // 19: api.squirrel.v1.SquirrelService.UploadSectionFile:input_type -> api.squirrel.v1.UploadSectionFileRequest
	8,  // 20: api.squirrel.v1.SquirrelService.ListSectionRows:input_type -> api.squirrel.v1.ListSectionRowsRequest
	10, // 21: api.squirrel.v1.SquirrelService.ClearSectionData:input_type -> api.squirrel.v1.ClearSectionDataRequest
	12, // 22: api.squirrel.v1.SquirrelService.StartReconcile:input_type -> api.squirrel.v1.StartReconcileRequest
	14, // 23: api.squirrel.v1.SquirrelService.GetReconcileStatus:input_type -> api.squirrel.v1.GetReconcileStatusRequest
	16, // 24: api.squirrel.v1.SquirrelService.ListReconcileRows:input_type -> api.squirrel.v1.ListReconcileRowsRequest
	18, // 25: api.squirrel.v1.SquirrelService.UpsertManualReview:input_type -> api.squirrel.v1.UpsertManualReviewRequest
	20, // 26: api.squirrel.v1.SquirrelService.ClearManualReviews:input_type -> api.squirrel.v1.ClearManualReviewsRequest
	22, // 27: api.squirrel.v1.SquirrelService.ListManualRemarkOptions:input_type -> api.squirrel.v1.ListManualRemarkOptionsRequest
	24, // 28: api.squirrel.v1.SquirrelService.DeleteManualRemarkOption:input_type -> api.squirrel.v1.DeleteManualRemarkOptionRequest
	1,  // 29: api.squirrel.v1.SquirrelService.ListTasks:output_type -> api.squirrel.v1.ListTasksReply
	3,  // 30: api.squirrel.v1.SquirrelService.CreateTask:output_type -> api.squirrel.v1.CreateTaskReply
	5,  // 31: api.squirrel.v1.SquirrelService.DeleteTask:output_type -> api.squirrel.v1.DeleteTaskReply
	7,  // 32: api.squirrel.v1.SquirrelService.UploadSectionFile:output_type -> api.squirrel.v1.UploadSectionFileReply
	9,  // 33: api.squirrel.v1.SquirrelService.ListSectionRows:output_type -> api.squirrel.v1.ListSectionRowsReply
	11, // 34: api.squirrel.v1.SquirrelService.ClearSectionData:output_type -> api.squirrel.v1.ClearSectionDataReply
	13, // 35: api.squirrel.v1.SquirrelService.StartReconcile:output_type -> api.squirrel.v1.StartReconcileReply
	15, // 36: api.squirrel.v1.SquirrelService.GetReconcileStatus:output_type -> api.squirrel.v1.GetReconcileStatusReply
	17, // 37: api.squirrel.v1.SquirrelService.ListReconcileRows:output_type -> api.squirrel.v1.ListReconcileRowsReply
	19, // 38: api.squirrel.v1.SquirrelService.UpsertManualReview:output_type -> api.squirrel.v1.UpsertManualReviewReply
	21, // 39: api.squirrel.v1.SquirrelService.ClearManualReviews:output_type -> api.squirrel.v1.ClearManualReviewsReply
	23, // 40: api.squirrel.v1.SquirrelService.ListManualRemarkOptions:output_type -> api.squirrel.v1.ListManualRemarkOptionsReply
	25, // 41: api.squirrel.v1.SquirrelService.DeleteManualRemarkOption:output_type -> api.squirrel.v1.DeleteManualRemarkOptionReply
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_squirrel_v1_squirrel_proto_init() }
func file_api_squirrel_v1_squirrel_proto_init() {
	if File_api_squirrel_v1_squirrel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_squirrel_v1_squirrel_proto_rawDesc), len(file_api_squirrel_v1_squirrel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_squirrel_v1_squirrel_proto_goTypes,
		DependencyIndexes: file_api_squirrel_v1_squirrel_proto_depIdxs,
		MessageInfos:      file_api_squirrel_v1_squirrel_proto_msgTypes,
	}.Build()
	File_api_squirrel_v1_squirrel_proto = out.File
	file_api_squirrel_v1_squirrel_proto_goTypes = nil
	file_api_squirrel_v1_squirrel_proto_depIdxs = nil
}
