// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"context"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/conf"
	"github.com/jeffinity/oculus/app/bookkeeping/internal/data"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

// initMigrator init db migrator.
func initMigrator(root context.Context, c *conf.Bootstrap, logger log.Logger) (*CmdMigrator, func(), error) {
	db, cleanup, err := data.NewGormPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	migrator := data.NewAllMigrator(db)
	cmdMigrator := NewMigrator(root, migrator)
	return cmdMigrator, func() {
		cleanup()
	}, nil
}
