// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"context"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/squirrel/internal/conf"
	"github.com/jeffinity/oculus/app/squirrel/internal/data"
)

// Injectors from wire.go:

// initMigrator init db migrator.
func initMigrator(root context.Context, c *conf.Bootstrap, logger log.Logger) (*CmdMigrator, func(), error) {
	db, err := data.NewPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	clusterClient, cleanup, err := data.NewRedis(root, c, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(c, db, clusterClient, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	migrator := data.NewAllMigrator(dataData)
	cmdMigrator := NewMigrator(root, migrator)
	return cmdMigrator, func() {
		cleanup2()
		cleanup()
	}, nil
}
