// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"context"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/squirrel/internal/biz"
	"github.com/jeffinity/oculus/app/squirrel/internal/conf"
	"github.com/jeffinity/oculus/app/squirrel/internal/data"
	"github.com/jeffinity/singularity/kratosx"
	"sync"
)

// Injectors from wire.go:

func InitTestResource(pcID kratosx.ServiceID, logger log.Logger, root context.Context, wg *sync.WaitGroup, c *conf.Bootstrap) (*Resource, func(), error) {
	db, err := data.NewPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	clusterClient, cleanup, err := data.NewRedis(root, c, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(c, db, clusterClient, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData, logger)
	helloUseCase := biz.NewHelloUseCase(helloRepo, logger)
	resource := newTestResource(root, logger, dataData, helloRepo, helloUseCase)
	return resource, func() {
		cleanup2()
		cleanup()
	}, nil
}
