// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/mh/v1/comic.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{0}
}

func (x *ListBooksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBooksRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListBooksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Items         []*BookListItem        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksReply) Reset() {
	*x = ListBooksReply{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksReply) ProtoMessage() {}

func (x *ListBooksReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksReply.ProtoReflect.Descriptor instead.
func (*ListBooksReply) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{1}
}

func (x *ListBooksReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBooksReply) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListBooksReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBooksReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListBooksReply) GetItems() []*BookListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BookListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	OrgId         int64                  `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Cover         map[string]string      `protobuf:"bytes,6,rep,name=cover,proto3" json:"cover,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListItem) Reset() {
	*x = BookListItem{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListItem) ProtoMessage() {}

func (x *BookListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListItem.ProtoReflect.Descriptor instead.
func (*BookListItem) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{2}
}

func (x *BookListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookListItem) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *BookListItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BookListItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *BookListItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *BookListItem) GetCover() map[string]string {
	if x != nil {
		return x.Cover
	}
	return nil
}

type ListLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestRequest) Reset() {
	*x = ListLatestRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestRequest) ProtoMessage() {}

func (x *ListLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestRequest.ProtoReflect.Descriptor instead.
func (*ListLatestRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{3}
}

func (x *ListLatestRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLatestRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListLatestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Items         []*LatestListItem      `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestReply) Reset() {
	*x = ListLatestReply{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestReply) ProtoMessage() {}

func (x *ListLatestReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestReply.ProtoReflect.Descriptor instead.
func (*ListLatestReply) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{4}
}

func (x *ListLatestReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLatestReply) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListLatestReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLatestReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListLatestReply) GetItems() []*LatestListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type LatestListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cname         string                 `protobuf:"bytes,1,opt,name=cname,proto3" json:"cname,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OrgId         int64                  `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Cid           int64                  `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	Prefix        string                 `protobuf:"bytes,5,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestListItem) Reset() {
	*x = LatestListItem{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestListItem) ProtoMessage() {}

func (x *LatestListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestListItem.ProtoReflect.Descriptor instead.
func (*LatestListItem) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{5}
}

func (x *LatestListItem) GetCname() string {
	if x != nil {
		return x.Cname
	}
	return ""
}

func (x *LatestListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LatestListItem) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *LatestListItem) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *LatestListItem) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *LatestListItem) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *LatestListItem) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

type GetBookReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *BookListItem          `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapters      []*ChapterMeta         `protobuf:"bytes,2,rep,name=chapters,proto3" json:"chapters,omitempty"`
	LastCid       int64                  `protobuf:"varint,3,opt,name=last_cid,json=lastCid,proto3" json:"last_cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookReply) Reset() {
	*x = GetBookReply{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookReply) ProtoMessage() {}

func (x *GetBookReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookReply.ProtoReflect.Descriptor instead.
func (*GetBookReply) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{7}
}

func (x *GetBookReply) GetBook() *BookListItem {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *GetBookReply) GetChapters() []*ChapterMeta {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *GetBookReply) GetLastCid() int64 {
	if x != nil {
		return x.LastCid
	}
	return 0
}

type ChapterMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int64                  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterMeta) Reset() {
	*x = ChapterMeta{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterMeta) ProtoMessage() {}

func (x *ChapterMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterMeta.ProtoReflect.Descriptor instead.
func (*ChapterMeta) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{8}
}

func (x *ChapterMeta) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ChapterMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChapterMeta) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type GetChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         int64                  `protobuf:"varint,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Cid           int64                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterRequest) Reset() {
	*x = GetChapterRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequest) ProtoMessage() {}

func (x *GetChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequest.ProtoReflect.Descriptor instead.
func (*GetChapterRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{9}
}

func (x *GetChapterRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *GetChapterRequest) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *GetChapterRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetChapterRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type GetChapterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterName   string                 `protobuf:"bytes,1,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	Cid           int64                  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	PrevCid       int64                  `protobuf:"varint,6,opt,name=prev_cid,json=prevCid,proto3" json:"prev_cid,omitempty"`
	NextCid       int64                  `protobuf:"varint,7,opt,name=next_cid,json=nextCid,proto3" json:"next_cid,omitempty"`
	Prefix        string                 `protobuf:"bytes,8,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Images        []string               `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterReply) Reset() {
	*x = GetChapterReply{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterReply) ProtoMessage() {}

func (x *GetChapterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterReply.ProtoReflect.Descriptor instead.
func (*GetChapterReply) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{10}
}

func (x *GetChapterReply) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *GetChapterReply) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *GetChapterReply) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetChapterReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetChapterReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetChapterReply) GetPrevCid() int64 {
	if x != nil {
		return x.PrevCid
	}
	return 0
}

func (x *GetChapterReply) GetNextCid() int64 {
	if x != nil {
		return x.NextCid
	}
	return 0
}

func (x *GetChapterReply) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *GetChapterReply) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{11}
}

type ProotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProotRequest) Reset() {
	*x = ProotRequest{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProotRequest) ProtoMessage() {}

func (x *ProotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProotRequest.ProtoReflect.Descriptor instead.
func (*ProotRequest) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{12}
}

type OperationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationReply) Reset() {
	*x = OperationReply{}
	mi := &file_api_mh_v1_comic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationReply) ProtoMessage() {}

func (x *OperationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_mh_v1_comic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationReply.ProtoReflect.Descriptor instead.
func (*OperationReply) Descriptor() ([]byte, []int) {
	return file_api_mh_v1_comic_proto_rawDescGZIP(), []int{13}
}

func (x *OperationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_mh_v1_comic_proto protoreflect.FileDescriptor

const file_api_mh_v1_comic_proto_rawDesc = "" +
	"\n" +
	"\x15api/mh/v1/comic.proto\x12\tapi.mh.v1\x1a\x1cgoogle/api/annotations.proto\":\n" +
	"\x10ListBooksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x9e\x01\n" +
	"\x0eListBooksReply\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12-\n" +
	"\x05items\x18\x05 \x03(\v2\x17.api.mh.v1.BookListItemR\x05items\"\x81\x02\n" +
	"\fBookListItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\x03R\x05orgId\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\tR\n" +
	"updateTime\x128\n" +
	"\x05cover\x18\x06 \x03(\v2\".api.mh.v1.BookListItem.CoverEntryR\x05cover\x1a8\n" +
	"\n" +
	"CoverEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x11ListLatestRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xa1\x01\n" +
	"\x0fListLatestReply\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12/\n" +
	"\x05items\x18\x05 \x03(\v2\x19.api.mh.v1.LatestListItemR\x05items\"\xbb\x01\n" +
	"\x0eLatestListItem\x12\x14\n" +
	"\x05cname\x18\x01 \x01(\tR\x05cname\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x03R\x05orgId\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\x03R\x03cid\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\tR\n" +
	"updateTime\"'\n" +
	"\x0eGetBookRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\"\x8a\x01\n" +
	"\fGetBookReply\x12+\n" +
	"\x04book\x18\x01 \x01(\v2\x17.api.mh.v1.BookListItemR\x04book\x122\n" +
	"\bchapters\x18\x02 \x03(\v2\x16.api.mh.v1.ChapterMetaR\bchapters\x12\x19\n" +
	"\blast_cid\x18\x03 \x01(\x03R\alastCid\"K\n" +
	"\vChapterMeta\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x03R\x03cid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\"j\n" +
	"\x11GetChapterRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\x03R\x05orgId\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x03R\x03cid\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\"\xf7\x01\n" +
	"\x0fGetChapterReply\x12!\n" +
	"\fchapter_name\x18\x01 \x01(\tR\vchapterName\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x03R\x03cid\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bprev_cid\x18\x06 \x01(\x03R\aprevCid\x12\x19\n" +
	"\bnext_cid\x18\a \x01(\x03R\anextCid\x12\x16\n" +
	"\x06prefix\x18\b \x01(\tR\x06prefix\x12\x16\n" +
	"\x06images\x18\t \x03(\tR\x06images\"\r\n" +
	"\vSyncRequest\"\x0e\n" +
	"\fProotRequest\"*\n" +
	"\x0eOperationReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbf\x04\n" +
	"\x0eMHComicService\x12]\n" +
	"\tListBooks\x12\x1b.api.mh.v1.ListBooksRequest\x1a\x19.api.mh.v1.ListBooksReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/mh/books\x12a\n" +
	"\n" +
	"ListLatest\x12\x1c.api.mh.v1.ListLatestRequest\x1a\x1a.api.mh.v1.ListLatestReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/mh/latest\x12V\n" +
	"\aGetBook\x12\x19.api.mh.v1.GetBookRequest\x1a\x17.api.mh.v1.GetBookReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/mh/book\x12b\n" +
	"\n" +
	"GetChapter\x12\x1c.api.mh.v1.GetChapterRequest\x1a\x1a.api.mh.v1.GetChapterReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/mh/chapter\x12U\n" +
	"\x04Sync\x12\x16.api.mh.v1.SyncRequest\x1a\x19.api.mh.v1.OperationReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/mh/sync\x12X\n" +
	"\x05Proot\x12\x17.api.mh.v1.ProotRequest\x1a\x19.api.mh.v1.OperationReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/mh/prootB\x8d\x01\n" +
	"\rcom.api.mh.v1B\n" +
	"ComicProtoP\x01Z*github.com/jeffinity/oculus/proto/mh/v1;v1\xa2\x02\x03AMX\xaa\x02\tApi.Mh.V1\xca\x02\tApi\\Mh\\V1\xe2\x02\x15Api\\Mh\\V1\\GPBMetadata\xea\x02\vApi::Mh::V1b\x06proto3"

var (
	file_api_mh_v1_comic_proto_rawDescOnce sync.Once
	file_api_mh_v1_comic_proto_rawDescData []byte
)

func file_api_mh_v1_comic_proto_rawDescGZIP() []byte {
	file_api_mh_v1_comic_proto_rawDescOnce.Do(func() {
		file_api_mh_v1_comic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_mh_v1_comic_proto_rawDesc), len(file_api_mh_v1_comic_proto_rawDesc)))
	})
	return file_api_mh_v1_comic_proto_rawDescData
}

var file_api_mh_v1_comic_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_mh_v1_comic_proto_goTypes = []any{
	(*ListBooksRequest)(nil),  // 0: api.mh.v1.ListBooksRequest
	(*ListBooksReply)(nil),    // 1: api.mh.v1.ListBooksReply
	(*BookListItem)(nil),      // 2: api.mh.v1.BookListItem
	(*ListLatestRequest)(nil), // 3: api.mh.v1.ListLatestRequest
	(*ListLatestReply)(nil),   // 4: api.mh.v1.ListLatestReply
	(*LatestListItem)(nil),    // 5: api.mh.v1.LatestListItem
	(*GetBookRequest)(nil),    // 6: api.mh.v1.GetBookRequest
	(*GetBookReply)(nil),      // 7: api.mh.v1.GetBookReply
	(*ChapterMeta)(nil),       // 8: api.mh.v1.ChapterMeta
	(*GetChapterRequest)(nil), // 9: api.mh.v1.GetChapterRequest
	(*GetChapterReply)(nil),   // 10: api.mh.v1.GetChapterReply
	(*SyncRequest)(nil),       // 11: api.mh.v1.SyncRequest
	(*ProotRequest)(nil),      // 12: api.mh.v1.ProotRequest
	(*OperationReply)(nil),    // 13: api.mh.v1.OperationReply
	nil,                       // 14: api.mh.v1.BookListItem.CoverEntry
}
var file_api_mh_v1_comic_proto_depIdxs = []int32{
	2,  // 0: api.mh.v1.ListBooksReply.items:type_name -> api.mh.v1.BookListItem
	14, // 1: api.mh.v1.BookListItem.cover:type_name -> api.mh.v1.BookListItem.CoverEntry
	5,  // 2: api.mh.v1.ListLatestReply.items:type_name -> api.mh.v1.LatestListItem
	2,  // 3: api.mh.v1.GetBookReply.book:type_name -> api.mh.v1.BookListItem
	8,  // 4: api.mh.v1.GetBookReply.chapters:type_name -> api.mh.v1.ChapterMeta
	0,  // 5: api.mh.v1.MHComicService.ListBooks:input_type -> api.mh.v1.ListBooksRequest
	3,  // 6: api.mh.v1.MHComicService.ListLatest:input_type -> api.mh.v1.ListLatestRequest
	6,  // 7: api.mh.v1.MHComicService.GetBook:input_type -> api.mh.v1.GetBookRequest
	9,  // 8: api.mh.v1.MHComicService.GetChapter:input_type -> api.mh.v1.GetChapterRequest
	11, // 9: api.mh.v1.MHComicService.Sync:input_type -> api.mh.v1.SyncRequest
	12, // 10: api.mh.v1.MHComicService.Proot:input_type -> api.mh.v1.ProotRequest
	1,  // 11: api.mh.v1.MHComicService.ListBooks:output_type -> api.mh.v1.ListBooksReply
	4,  // 12: api.mh.v1.MHComicService.ListLatest:output_type -> api.mh.v1.ListLatestReply
	7,  // 13: api.mh.v1.MHComicService.GetBook:output_type -> api.mh.v1.GetBookReply
	10, // 14: api.mh.v1.MHComicService.GetChapter:output_type -> api.mh.v1.GetChapterReply
	13, // 15: api.mh.v1.MHComicService.Sync:output_type -> api.mh.v1.OperationReply
	13, // 16: api.mh.v1.MHComicService.Proot:output_type -> api.mh.v1.OperationReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_mh_v1_comic_proto_init() }
func file_api_mh_v1_comic_proto_init() {
	if File_api_mh_v1_comic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_mh_v1_comic_proto_rawDesc), len(file_api_mh_v1_comic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mh_v1_comic_proto_goTypes,
		DependencyIndexes: file_api_mh_v1_comic_proto_depIdxs,
		MessageInfos:      file_api_mh_v1_comic_proto_msgTypes,
	}.Build()
	File_api_mh_v1_comic_proto = out.File
	file_api_mh_v1_comic_proto_goTypes = nil
	file_api_mh_v1_comic_proto_depIdxs = nil
}
