// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/mh/v1/comic.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MHComicService_ListBooks_FullMethodName  = "/api.mh.v1.MHComicService/ListBooks"
	MHComicService_ListLatest_FullMethodName = "/api.mh.v1.MHComicService/ListLatest"
	MHComicService_GetBook_FullMethodName    = "/api.mh.v1.MHComicService/GetBook"
	MHComicService_GetChapter_FullMethodName = "/api.mh.v1.MHComicService/GetChapter"
	MHComicService_Sync_FullMethodName       = "/api.mh.v1.MHComicService/Sync"
	MHComicService_Proot_FullMethodName      = "/api.mh.v1.MHComicService/Proot"
	MHComicService_SetStar_FullMethodName    = "/api.mh.v1.MHComicService/SetStar"
)

// MHComicServiceClient is the client API for MHComicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MHComicServiceClient interface {
	// 查询漫画列表
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksReply, error)
	// 查询最新章节列表
	ListLatest(ctx context.Context, in *ListLatestRequest, opts ...grpc.CallOption) (*ListLatestReply, error)
	// 查询漫画目录
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookReply, error)
	// 查询章节详情
	GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*GetChapterReply, error)
	// 同步增量章节
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*OperationReply, error)
	// 反查并补全漫画信息
	Proot(ctx context.Context, in *ProotRequest, opts ...grpc.CallOption) (*OperationReply, error)
	// 设置漫画星标
	SetStar(ctx context.Context, in *SetStarRequest, opts ...grpc.CallOption) (*SetStarReply, error)
}

type mHComicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMHComicServiceClient(cc grpc.ClientConnInterface) MHComicServiceClient {
	return &mHComicServiceClient{cc}
}

func (c *mHComicServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBooksReply)
	err := c.cc.Invoke(ctx, MHComicService_ListBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) ListLatest(ctx context.Context, in *ListLatestRequest, opts ...grpc.CallOption) (*ListLatestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLatestReply)
	err := c.cc.Invoke(ctx, MHComicService_ListLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBookReply)
	err := c.cc.Invoke(ctx, MHComicService_GetBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*GetChapterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChapterReply)
	err := c.cc.Invoke(ctx, MHComicService_GetChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationReply)
	err := c.cc.Invoke(ctx, MHComicService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) Proot(ctx context.Context, in *ProotRequest, opts ...grpc.CallOption) (*OperationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationReply)
	err := c.cc.Invoke(ctx, MHComicService_Proot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mHComicServiceClient) SetStar(ctx context.Context, in *SetStarRequest, opts ...grpc.CallOption) (*SetStarReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetStarReply)
	err := c.cc.Invoke(ctx, MHComicService_SetStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MHComicServiceServer is the server API for MHComicService service.
// All implementations must embed UnimplementedMHComicServiceServer
// for forward compatibility.
type MHComicServiceServer interface {
	// 查询漫画列表
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksReply, error)
	// 查询最新章节列表
	ListLatest(context.Context, *ListLatestRequest) (*ListLatestReply, error)
	// 查询漫画目录
	GetBook(context.Context, *GetBookRequest) (*GetBookReply, error)
	// 查询章节详情
	GetChapter(context.Context, *GetChapterRequest) (*GetChapterReply, error)
	// 同步增量章节
	Sync(context.Context, *SyncRequest) (*OperationReply, error)
	// 反查并补全漫画信息
	Proot(context.Context, *ProotRequest) (*OperationReply, error)
	// 设置漫画星标
	SetStar(context.Context, *SetStarRequest) (*SetStarReply, error)
	mustEmbedUnimplementedMHComicServiceServer()
}

// UnimplementedMHComicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMHComicServiceServer struct{}

func (UnimplementedMHComicServiceServer) ListBooks(context.Context, *ListBooksRequest) (*ListBooksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBooks not implemented")
}
func (UnimplementedMHComicServiceServer) ListLatest(context.Context, *ListLatestRequest) (*ListLatestReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLatest not implemented")
}
func (UnimplementedMHComicServiceServer) GetBook(context.Context, *GetBookRequest) (*GetBookReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedMHComicServiceServer) GetChapter(context.Context, *GetChapterRequest) (*GetChapterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChapter not implemented")
}
func (UnimplementedMHComicServiceServer) Sync(context.Context, *SyncRequest) (*OperationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedMHComicServiceServer) Proot(context.Context, *ProotRequest) (*OperationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Proot not implemented")
}
func (UnimplementedMHComicServiceServer) SetStar(context.Context, *SetStarRequest) (*SetStarReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStar not implemented")
}
func (UnimplementedMHComicServiceServer) mustEmbedUnimplementedMHComicServiceServer() {}
func (UnimplementedMHComicServiceServer) testEmbeddedByValue()                        {}

// UnsafeMHComicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MHComicServiceServer will
// result in compilation errors.
type UnsafeMHComicServiceServer interface {
	mustEmbedUnimplementedMHComicServiceServer()
}

func RegisterMHComicServiceServer(s grpc.ServiceRegistrar, srv MHComicServiceServer) {
	// If the following call panics, it indicates UnimplementedMHComicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MHComicService_ServiceDesc, srv)
}

func _MHComicService_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_ListBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_ListLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).ListLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_ListLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).ListLatest(ctx, req.(*ListLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_GetBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_GetChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).GetChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_GetChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).GetChapter(ctx, req.(*GetChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_Proot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).Proot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_Proot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).Proot(ctx, req.(*ProotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MHComicService_SetStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MHComicServiceServer).SetStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MHComicService_SetStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MHComicServiceServer).SetStar(ctx, req.(*SetStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MHComicService_ServiceDesc is the grpc.ServiceDesc for MHComicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MHComicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.mh.v1.MHComicService",
	HandlerType: (*MHComicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBooks",
			Handler:    _MHComicService_ListBooks_Handler,
		},
		{
			MethodName: "ListLatest",
			Handler:    _MHComicService_ListLatest_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _MHComicService_GetBook_Handler,
		},
		{
			MethodName: "GetChapter",
			Handler:    _MHComicService_GetChapter_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _MHComicService_Sync_Handler,
		},
		{
			MethodName: "Proot",
			Handler:    _MHComicService_Proot_Handler,
		},
		{
			MethodName: "SetStar",
			Handler:    _MHComicService_SetStar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mh/v1/comic.proto",
}
