// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/mh/v1/comic.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMHComicServiceGetBook = "/api.mh.v1.MHComicService/GetBook"
const OperationMHComicServiceGetChapter = "/api.mh.v1.MHComicService/GetChapter"
const OperationMHComicServiceListBooks = "/api.mh.v1.MHComicService/ListBooks"
const OperationMHComicServiceListLatest = "/api.mh.v1.MHComicService/ListLatest"
const OperationMHComicServiceProot = "/api.mh.v1.MHComicService/Proot"
const OperationMHComicServiceSync = "/api.mh.v1.MHComicService/Sync"

type MHComicServiceHTTPServer interface {
	// GetBook 查询漫画目录
	GetBook(context.Context, *GetBookRequest) (*GetBookReply, error)
	// GetChapter 查询章节详情
	GetChapter(context.Context, *GetChapterRequest) (*GetChapterReply, error)
	// ListBooks 查询漫画列表
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksReply, error)
	// ListLatest 查询最新章节列表
	ListLatest(context.Context, *ListLatestRequest) (*ListLatestReply, error)
	// Proot 反查并补全漫画信息
	Proot(context.Context, *ProotRequest) (*OperationReply, error)
	// Sync 同步增量章节
	Sync(context.Context, *SyncRequest) (*OperationReply, error)
}

func RegisterMHComicServiceHTTPServer(s *http.Server, srv MHComicServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/mh/books", _MHComicService_ListBooks0_HTTP_Handler(srv))
	r.GET("/api/v1/mh/latest", _MHComicService_ListLatest0_HTTP_Handler(srv))
	r.GET("/api/v1/mh/book", _MHComicService_GetBook0_HTTP_Handler(srv))
	r.GET("/api/v1/mh/chapter", _MHComicService_GetChapter0_HTTP_Handler(srv))
	r.POST("/api/v1/mh/sync", _MHComicService_Sync0_HTTP_Handler(srv))
	r.POST("/api/v1/mh/proot", _MHComicService_Proot0_HTTP_Handler(srv))
}

func _MHComicService_ListBooks0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBooksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceListBooks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBooks(ctx, req.(*ListBooksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBooksReply)
		return ctx.Result(200, reply)
	}
}

func _MHComicService_ListLatest0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLatestRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceListLatest)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLatest(ctx, req.(*ListLatestRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLatestReply)
		return ctx.Result(200, reply)
	}
}

func _MHComicService_GetBook0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBookRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceGetBook)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBook(ctx, req.(*GetBookRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBookReply)
		return ctx.Result(200, reply)
	}
}

func _MHComicService_GetChapter0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChapterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceGetChapter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChapter(ctx, req.(*GetChapterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetChapterReply)
		return ctx.Result(200, reply)
	}
}

func _MHComicService_Sync0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceSync)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Sync(ctx, req.(*SyncRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationReply)
		return ctx.Result(200, reply)
	}
}

func _MHComicService_Proot0_HTTP_Handler(srv MHComicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMHComicServiceProot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Proot(ctx, req.(*ProotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationReply)
		return ctx.Result(200, reply)
	}
}

type MHComicServiceHTTPClient interface {
	// GetBook 查询漫画目录
	GetBook(ctx context.Context, req *GetBookRequest, opts ...http.CallOption) (rsp *GetBookReply, err error)
	// GetChapter 查询章节详情
	GetChapter(ctx context.Context, req *GetChapterRequest, opts ...http.CallOption) (rsp *GetChapterReply, err error)
	// ListBooks 查询漫画列表
	ListBooks(ctx context.Context, req *ListBooksRequest, opts ...http.CallOption) (rsp *ListBooksReply, err error)
	// ListLatest 查询最新章节列表
	ListLatest(ctx context.Context, req *ListLatestRequest, opts ...http.CallOption) (rsp *ListLatestReply, err error)
	// Proot 反查并补全漫画信息
	Proot(ctx context.Context, req *ProotRequest, opts ...http.CallOption) (rsp *OperationReply, err error)
	// Sync 同步增量章节
	Sync(ctx context.Context, req *SyncRequest, opts ...http.CallOption) (rsp *OperationReply, err error)
}

type MHComicServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMHComicServiceHTTPClient(client *http.Client) MHComicServiceHTTPClient {
	return &MHComicServiceHTTPClientImpl{client}
}

// GetBook 查询漫画目录
func (c *MHComicServiceHTTPClientImpl) GetBook(ctx context.Context, in *GetBookRequest, opts ...http.CallOption) (*GetBookReply, error) {
	var out GetBookReply
	pattern := "/api/v1/mh/book"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMHComicServiceGetBook))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChapter 查询章节详情
func (c *MHComicServiceHTTPClientImpl) GetChapter(ctx context.Context, in *GetChapterRequest, opts ...http.CallOption) (*GetChapterReply, error) {
	var out GetChapterReply
	pattern := "/api/v1/mh/chapter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMHComicServiceGetChapter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBooks 查询漫画列表
func (c *MHComicServiceHTTPClientImpl) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...http.CallOption) (*ListBooksReply, error) {
	var out ListBooksReply
	pattern := "/api/v1/mh/books"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMHComicServiceListBooks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLatest 查询最新章节列表
func (c *MHComicServiceHTTPClientImpl) ListLatest(ctx context.Context, in *ListLatestRequest, opts ...http.CallOption) (*ListLatestReply, error) {
	var out ListLatestReply
	pattern := "/api/v1/mh/latest"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMHComicServiceListLatest))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Proot 反查并补全漫画信息
func (c *MHComicServiceHTTPClientImpl) Proot(ctx context.Context, in *ProotRequest, opts ...http.CallOption) (*OperationReply, error) {
	var out OperationReply
	pattern := "/api/v1/mh/proot"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMHComicServiceProot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Sync 同步增量章节
func (c *MHComicServiceHTTPClientImpl) Sync(ctx context.Context, in *SyncRequest, opts ...http.CallOption) (*OperationReply, error) {
	var out OperationReply
	pattern := "/api/v1/mh/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMHComicServiceSync))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
