// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jeffinity/oculus/app/squirrel/internal/app_init"
	"github.com/jeffinity/oculus/app/squirrel/internal/biz"
	"github.com/jeffinity/oculus/app/squirrel/internal/conf"
	"github.com/jeffinity/oculus/app/squirrel/internal/data"
	"github.com/jeffinity/oculus/app/squirrel/internal/server"
	"github.com/jeffinity/oculus/app/squirrel/internal/service"
	"github.com/jeffinity/singularity/kratosx"
	"github.com/jeffinity/singularity/nacosx"
	"sync"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(pcID kratosx.ServiceID, root context.Context, c *conf.Bootstrap, wg *sync.WaitGroup, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewPostgres(c, logger)
	if err != nil {
		return nil, nil, err
	}
	clusterClient, cleanup, err := data.NewRedis(root, c, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(c, db, clusterClient, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData, logger)
	helloUseCase := biz.NewHelloUseCase(helloRepo, logger)
	healthService := service.NewHealthService(logger, c, helloUseCase)
	squirrelRepo := data.NewSquirrelRepo(dataData, logger)
	squirrelService := service.NewSquirrelService(squirrelRepo, logger)
	grpcServer := server.NewGRPCServer(c, healthService, squirrelService, logger)
	httpServer := server.NewHTTPServer(c, healthService, squirrelService, logger)
	nacosxConf := app_init.NewNacosConf(c)
	iNamingClient, err := nacosx.NewNamingClient(nacosxConf)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry, err := nacosx.NewRegistryEngine(nacosxConf, iNamingClient)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, err := newApp(pcID, logger, c, grpcServer, httpServer, registry)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
