// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/bookkeeping/v1/bookkeeping.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBookkeepingServiceAddLoanPrepayment = "/api.bookkeeping.v1.BookkeepingService/AddLoanPrepayment"
const OperationBookkeepingServiceAdjustLoanRate = "/api.bookkeeping.v1.BookkeepingService/AdjustLoanRate"
const OperationBookkeepingServiceAssetList = "/api.bookkeeping.v1.BookkeepingService/AssetList"
const OperationBookkeepingServiceCreateMortgageLoan = "/api.bookkeeping.v1.BookkeepingService/CreateMortgageLoan"
const OperationBookkeepingServiceLedgerList = "/api.bookkeeping.v1.BookkeepingService/LedgerList"
const OperationBookkeepingServiceLedgerStats = "/api.bookkeeping.v1.BookkeepingService/LedgerStats"
const OperationBookkeepingServiceLoanDetail = "/api.bookkeeping.v1.BookkeepingService/LoanDetail"
const OperationBookkeepingServiceLoanSummaryList = "/api.bookkeeping.v1.BookkeepingService/LoanSummaryList"
const OperationBookkeepingServiceStartLoanRepayment = "/api.bookkeeping.v1.BookkeepingService/StartLoanRepayment"
const OperationBookkeepingServiceUpsertLedgerEntry = "/api.bookkeeping.v1.BookkeepingService/UpsertLedgerEntry"

type BookkeepingServiceHTTPServer interface {
	// AddLoanPrepayment 新增提前还款记录（按指定方式重算后续还款计划）
	AddLoanPrepayment(context.Context, *AddLoanPrepaymentRequest) (*AddLoanPrepaymentReply, error)
	// AdjustLoanRate 调整贷款利率（从指定年月起生效，重算后续还款计划）
	AdjustLoanRate(context.Context, *AdjustLoanRateRequest) (*AdjustLoanRateReply, error)
	// AssetList 查询资产列表（按月份聚合，返回资产、负债、净资产及贷款明细）
	AssetList(context.Context, *AssetListRequest) (*AssetListReply, error)
	// CreateMortgageLoan 创建房贷（等额本息）
	CreateMortgageLoan(context.Context, *CreateMortgageLoanRequest) (*CreateMortgageLoanReply, error)
	// LedgerList 查询某月账本清单
	LedgerList(context.Context, *LedgerListRequest) (*LedgerListReply, error)
	// LedgerStats 查询账单统计（支持按月/按年趋势与支出排行榜）
	LedgerStats(context.Context, *LedgerStatsRequest) (*LedgerStatsReply, error)
	// LoanDetail 查询贷款详情（含下次还款日起未来N个月计划）
	LoanDetail(context.Context, *LoanDetailRequest) (*LoanDetailReply, error)
	// LoanSummaryList 查询贷款汇总列表
	LoanSummaryList(context.Context, *LoanSummaryListRequest) (*LoanSummaryListReply, error)
	// StartLoanRepayment 设置贷款开始还款时间
	StartLoanRepayment(context.Context, *StartLoanRepaymentRequest) (*StartLoanRepaymentReply, error)
	// UpsertLedgerEntry 新增或更新账本记录（按日期+类别+金额唯一更新）
	UpsertLedgerEntry(context.Context, *UpsertLedgerEntryRequest) (*UpsertLedgerEntryReply, error)
}

func RegisterBookkeepingServiceHTTPServer(s *http.Server, srv BookkeepingServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/bookkeeping/assets", _BookkeepingService_AssetList0_HTTP_Handler(srv))
	r.POST("/api/v1/bookkeeping/ledgers", _BookkeepingService_UpsertLedgerEntry0_HTTP_Handler(srv))
	r.GET("/api/v1/bookkeeping/ledgers", _BookkeepingService_LedgerList0_HTTP_Handler(srv))
	r.GET("/api/v1/bookkeeping/ledgers/stats", _BookkeepingService_LedgerStats0_HTTP_Handler(srv))
	r.POST("/api/v1/bookkeeping/loans/mortgage", _BookkeepingService_CreateMortgageLoan0_HTTP_Handler(srv))
	r.POST("/api/v1/bookkeeping/loans/{loan_id}/start-repayment", _BookkeepingService_StartLoanRepayment0_HTTP_Handler(srv))
	r.POST("/api/v1/bookkeeping/loans/{loan_id}/rate-adjustments", _BookkeepingService_AdjustLoanRate0_HTTP_Handler(srv))
	r.POST("/api/v1/bookkeeping/loans/{loan_id}/prepayments", _BookkeepingService_AddLoanPrepayment0_HTTP_Handler(srv))
	r.GET("/api/v1/bookkeeping/loans", _BookkeepingService_LoanSummaryList0_HTTP_Handler(srv))
	r.GET("/api/v1/bookkeeping/loans/{loan_id}", _BookkeepingService_LoanDetail0_HTTP_Handler(srv))
}

func _BookkeepingService_AssetList0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssetListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceAssetList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssetList(ctx, req.(*AssetListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssetListReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_UpsertLedgerEntry0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertLedgerEntryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceUpsertLedgerEntry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertLedgerEntry(ctx, req.(*UpsertLedgerEntryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertLedgerEntryReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_LedgerList0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LedgerListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceLedgerList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LedgerList(ctx, req.(*LedgerListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LedgerListReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_LedgerStats0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LedgerStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceLedgerStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LedgerStats(ctx, req.(*LedgerStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LedgerStatsReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_CreateMortgageLoan0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMortgageLoanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceCreateMortgageLoan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMortgageLoan(ctx, req.(*CreateMortgageLoanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateMortgageLoanReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_StartLoanRepayment0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLoanRepaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceStartLoanRepayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLoanRepayment(ctx, req.(*StartLoanRepaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartLoanRepaymentReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_AdjustLoanRate0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdjustLoanRateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceAdjustLoanRate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdjustLoanRate(ctx, req.(*AdjustLoanRateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdjustLoanRateReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_AddLoanPrepayment0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddLoanPrepaymentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceAddLoanPrepayment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddLoanPrepayment(ctx, req.(*AddLoanPrepaymentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddLoanPrepaymentReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_LoanSummaryList0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoanSummaryListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceLoanSummaryList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoanSummaryList(ctx, req.(*LoanSummaryListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoanSummaryListReply)
		return ctx.Result(200, reply)
	}
}

func _BookkeepingService_LoanDetail0_HTTP_Handler(srv BookkeepingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoanDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBookkeepingServiceLoanDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoanDetail(ctx, req.(*LoanDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoanDetailReply)
		return ctx.Result(200, reply)
	}
}

type BookkeepingServiceHTTPClient interface {
	// AddLoanPrepayment 新增提前还款记录（按指定方式重算后续还款计划）
	AddLoanPrepayment(ctx context.Context, req *AddLoanPrepaymentRequest, opts ...http.CallOption) (rsp *AddLoanPrepaymentReply, err error)
	// AdjustLoanRate 调整贷款利率（从指定年月起生效，重算后续还款计划）
	AdjustLoanRate(ctx context.Context, req *AdjustLoanRateRequest, opts ...http.CallOption) (rsp *AdjustLoanRateReply, err error)
	// AssetList 查询资产列表（按月份聚合，返回资产、负债、净资产及贷款明细）
	AssetList(ctx context.Context, req *AssetListRequest, opts ...http.CallOption) (rsp *AssetListReply, err error)
	// CreateMortgageLoan 创建房贷（等额本息）
	CreateMortgageLoan(ctx context.Context, req *CreateMortgageLoanRequest, opts ...http.CallOption) (rsp *CreateMortgageLoanReply, err error)
	// LedgerList 查询某月账本清单
	LedgerList(ctx context.Context, req *LedgerListRequest, opts ...http.CallOption) (rsp *LedgerListReply, err error)
	// LedgerStats 查询账单统计（支持按月/按年趋势与支出排行榜）
	LedgerStats(ctx context.Context, req *LedgerStatsRequest, opts ...http.CallOption) (rsp *LedgerStatsReply, err error)
	// LoanDetail 查询贷款详情（含下次还款日起未来N个月计划）
	LoanDetail(ctx context.Context, req *LoanDetailRequest, opts ...http.CallOption) (rsp *LoanDetailReply, err error)
	// LoanSummaryList 查询贷款汇总列表
	LoanSummaryList(ctx context.Context, req *LoanSummaryListRequest, opts ...http.CallOption) (rsp *LoanSummaryListReply, err error)
	// StartLoanRepayment 设置贷款开始还款时间
	StartLoanRepayment(ctx context.Context, req *StartLoanRepaymentRequest, opts ...http.CallOption) (rsp *StartLoanRepaymentReply, err error)
	// UpsertLedgerEntry 新增或更新账本记录（按日期+类别+金额唯一更新）
	UpsertLedgerEntry(ctx context.Context, req *UpsertLedgerEntryRequest, opts ...http.CallOption) (rsp *UpsertLedgerEntryReply, err error)
}

type BookkeepingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBookkeepingServiceHTTPClient(client *http.Client) BookkeepingServiceHTTPClient {
	return &BookkeepingServiceHTTPClientImpl{client}
}

// AddLoanPrepayment 新增提前还款记录（按指定方式重算后续还款计划）
func (c *BookkeepingServiceHTTPClientImpl) AddLoanPrepayment(ctx context.Context, in *AddLoanPrepaymentRequest, opts ...http.CallOption) (*AddLoanPrepaymentReply, error) {
	var out AddLoanPrepaymentReply
	pattern := "/api/v1/bookkeeping/loans/{loan_id}/prepayments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookkeepingServiceAddLoanPrepayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AdjustLoanRate 调整贷款利率（从指定年月起生效，重算后续还款计划）
func (c *BookkeepingServiceHTTPClientImpl) AdjustLoanRate(ctx context.Context, in *AdjustLoanRateRequest, opts ...http.CallOption) (*AdjustLoanRateReply, error) {
	var out AdjustLoanRateReply
	pattern := "/api/v1/bookkeeping/loans/{loan_id}/rate-adjustments"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookkeepingServiceAdjustLoanRate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssetList 查询资产列表（按月份聚合，返回资产、负债、净资产及贷款明细）
func (c *BookkeepingServiceHTTPClientImpl) AssetList(ctx context.Context, in *AssetListRequest, opts ...http.CallOption) (*AssetListReply, error) {
	var out AssetListReply
	pattern := "/api/v1/bookkeeping/assets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookkeepingServiceAssetList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateMortgageLoan 创建房贷（等额本息）
func (c *BookkeepingServiceHTTPClientImpl) CreateMortgageLoan(ctx context.Context, in *CreateMortgageLoanRequest, opts ...http.CallOption) (*CreateMortgageLoanReply, error) {
	var out CreateMortgageLoanReply
	pattern := "/api/v1/bookkeeping/loans/mortgage"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookkeepingServiceCreateMortgageLoan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LedgerList 查询某月账本清单
func (c *BookkeepingServiceHTTPClientImpl) LedgerList(ctx context.Context, in *LedgerListRequest, opts ...http.CallOption) (*LedgerListReply, error) {
	var out LedgerListReply
	pattern := "/api/v1/bookkeeping/ledgers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookkeepingServiceLedgerList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LedgerStats 查询账单统计（支持按月/按年趋势与支出排行榜）
func (c *BookkeepingServiceHTTPClientImpl) LedgerStats(ctx context.Context, in *LedgerStatsRequest, opts ...http.CallOption) (*LedgerStatsReply, error) {
	var out LedgerStatsReply
	pattern := "/api/v1/bookkeeping/ledgers/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookkeepingServiceLedgerStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoanDetail 查询贷款详情（含下次还款日起未来N个月计划）
func (c *BookkeepingServiceHTTPClientImpl) LoanDetail(ctx context.Context, in *LoanDetailRequest, opts ...http.CallOption) (*LoanDetailReply, error) {
	var out LoanDetailReply
	pattern := "/api/v1/bookkeeping/loans/{loan_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookkeepingServiceLoanDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoanSummaryList 查询贷款汇总列表
func (c *BookkeepingServiceHTTPClientImpl) LoanSummaryList(ctx context.Context, in *LoanSummaryListRequest, opts ...http.CallOption) (*LoanSummaryListReply, error) {
	var out LoanSummaryListReply
	pattern := "/api/v1/bookkeeping/loans"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBookkeepingServiceLoanSummaryList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartLoanRepayment 设置贷款开始还款时间
func (c *BookkeepingServiceHTTPClientImpl) StartLoanRepayment(ctx context.Context, in *StartLoanRepaymentRequest, opts ...http.CallOption) (*StartLoanRepaymentReply, error) {
	var out StartLoanRepaymentReply
	pattern := "/api/v1/bookkeeping/loans/{loan_id}/start-repayment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookkeepingServiceStartLoanRepayment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpsertLedgerEntry 新增或更新账本记录（按日期+类别+金额唯一更新）
func (c *BookkeepingServiceHTTPClientImpl) UpsertLedgerEntry(ctx context.Context, in *UpsertLedgerEntryRequest, opts ...http.CallOption) (*UpsertLedgerEntryReply, error) {
	var out UpsertLedgerEntryReply
	pattern := "/api/v1/bookkeeping/ledgers"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBookkeepingServiceUpsertLedgerEntry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
