// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: api/bookkeeping/v1/bookkeeping.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookkeepingService_AssetList_FullMethodName          = "/api.bookkeeping.v1.BookkeepingService/AssetList"
	BookkeepingService_AssetDetailList_FullMethodName    = "/api.bookkeeping.v1.BookkeepingService/AssetDetailList"
	BookkeepingService_CreateAssetDetail_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/CreateAssetDetail"
	BookkeepingService_UpdateAssetDetail_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/UpdateAssetDetail"
	BookkeepingService_DeleteAssetDetail_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/DeleteAssetDetail"
	BookkeepingService_UpdateAssetRemark_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/UpdateAssetRemark"
	BookkeepingService_UpsertLedgerEntry_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/UpsertLedgerEntry"
	BookkeepingService_LedgerList_FullMethodName         = "/api.bookkeeping.v1.BookkeepingService/LedgerList"
	BookkeepingService_LedgerStats_FullMethodName        = "/api.bookkeeping.v1.BookkeepingService/LedgerStats"
	BookkeepingService_CreateMortgageLoan_FullMethodName = "/api.bookkeeping.v1.BookkeepingService/CreateMortgageLoan"
	BookkeepingService_StartLoanRepayment_FullMethodName = "/api.bookkeeping.v1.BookkeepingService/StartLoanRepayment"
	BookkeepingService_AdjustLoanRate_FullMethodName     = "/api.bookkeeping.v1.BookkeepingService/AdjustLoanRate"
	BookkeepingService_AddLoanPrepayment_FullMethodName  = "/api.bookkeeping.v1.BookkeepingService/AddLoanPrepayment"
	BookkeepingService_LoanSummaryList_FullMethodName    = "/api.bookkeeping.v1.BookkeepingService/LoanSummaryList"
	BookkeepingService_LoanDetail_FullMethodName         = "/api.bookkeeping.v1.BookkeepingService/LoanDetail"
)

// BookkeepingServiceClient is the client API for BookkeepingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookkeepingServiceClient interface {
	// 查询资产列表（按月份聚合，返回资产、负债、净资产及贷款明细）
	AssetList(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListReply, error)
	// 查询某月资产明细（若当月为空且上月存在，会自动复制一份上月数据到当月）
	AssetDetailList(ctx context.Context, in *AssetDetailListRequest, opts ...grpc.CallOption) (*AssetDetailListReply, error)
	// 新增资产明细
	CreateAssetDetail(ctx context.Context, in *CreateAssetDetailRequest, opts ...grpc.CallOption) (*CreateAssetDetailReply, error)
	// 更新资产明细
	UpdateAssetDetail(ctx context.Context, in *UpdateAssetDetailRequest, opts ...grpc.CallOption) (*UpdateAssetDetailReply, error)
	// 删除资产明细
	DeleteAssetDetail(ctx context.Context, in *DeleteAssetDetailRequest, opts ...grpc.CallOption) (*DeleteAssetDetailReply, error)
	// 更新某月资产备注
	UpdateAssetRemark(ctx context.Context, in *UpdateAssetRemarkRequest, opts ...grpc.CallOption) (*UpdateAssetRemarkReply, error)
	// 新增或更新账本记录（按日期+类别+金额唯一更新）
	UpsertLedgerEntry(ctx context.Context, in *UpsertLedgerEntryRequest, opts ...grpc.CallOption) (*UpsertLedgerEntryReply, error)
	// 查询某月账本清单
	LedgerList(ctx context.Context, in *LedgerListRequest, opts ...grpc.CallOption) (*LedgerListReply, error)
	// 查询账单统计（支持按月/按年趋势与支出排行榜）
	LedgerStats(ctx context.Context, in *LedgerStatsRequest, opts ...grpc.CallOption) (*LedgerStatsReply, error)
	// 创建房贷（等额本息）
	CreateMortgageLoan(ctx context.Context, in *CreateMortgageLoanRequest, opts ...grpc.CallOption) (*CreateMortgageLoanReply, error)
	// 设置贷款开始还款时间
	StartLoanRepayment(ctx context.Context, in *StartLoanRepaymentRequest, opts ...grpc.CallOption) (*StartLoanRepaymentReply, error)
	// 调整贷款利率（从指定年月起生效，重算后续还款计划）
	AdjustLoanRate(ctx context.Context, in *AdjustLoanRateRequest, opts ...grpc.CallOption) (*AdjustLoanRateReply, error)
	// 新增提前还款记录（按指定方式重算后续还款计划）
	AddLoanPrepayment(ctx context.Context, in *AddLoanPrepaymentRequest, opts ...grpc.CallOption) (*AddLoanPrepaymentReply, error)
	// 查询贷款汇总列表
	LoanSummaryList(ctx context.Context, in *LoanSummaryListRequest, opts ...grpc.CallOption) (*LoanSummaryListReply, error)
	// 查询贷款详情（含下次还款日起未来N个月计划）
	LoanDetail(ctx context.Context, in *LoanDetailRequest, opts ...grpc.CallOption) (*LoanDetailReply, error)
}

type bookkeepingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookkeepingServiceClient(cc grpc.ClientConnInterface) BookkeepingServiceClient {
	return &bookkeepingServiceClient{cc}
}

func (c *bookkeepingServiceClient) AssetList(ctx context.Context, in *AssetListRequest, opts ...grpc.CallOption) (*AssetListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetListReply)
	err := c.cc.Invoke(ctx, BookkeepingService_AssetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) AssetDetailList(ctx context.Context, in *AssetDetailListRequest, opts ...grpc.CallOption) (*AssetDetailListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetDetailListReply)
	err := c.cc.Invoke(ctx, BookkeepingService_AssetDetailList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) CreateAssetDetail(ctx context.Context, in *CreateAssetDetailRequest, opts ...grpc.CallOption) (*CreateAssetDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetDetailReply)
	err := c.cc.Invoke(ctx, BookkeepingService_CreateAssetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) UpdateAssetDetail(ctx context.Context, in *UpdateAssetDetailRequest, opts ...grpc.CallOption) (*UpdateAssetDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssetDetailReply)
	err := c.cc.Invoke(ctx, BookkeepingService_UpdateAssetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) DeleteAssetDetail(ctx context.Context, in *DeleteAssetDetailRequest, opts ...grpc.CallOption) (*DeleteAssetDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssetDetailReply)
	err := c.cc.Invoke(ctx, BookkeepingService_DeleteAssetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) UpdateAssetRemark(ctx context.Context, in *UpdateAssetRemarkRequest, opts ...grpc.CallOption) (*UpdateAssetRemarkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssetRemarkReply)
	err := c.cc.Invoke(ctx, BookkeepingService_UpdateAssetRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) UpsertLedgerEntry(ctx context.Context, in *UpsertLedgerEntryRequest, opts ...grpc.CallOption) (*UpsertLedgerEntryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertLedgerEntryReply)
	err := c.cc.Invoke(ctx, BookkeepingService_UpsertLedgerEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) LedgerList(ctx context.Context, in *LedgerListRequest, opts ...grpc.CallOption) (*LedgerListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerListReply)
	err := c.cc.Invoke(ctx, BookkeepingService_LedgerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) LedgerStats(ctx context.Context, in *LedgerStatsRequest, opts ...grpc.CallOption) (*LedgerStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerStatsReply)
	err := c.cc.Invoke(ctx, BookkeepingService_LedgerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) CreateMortgageLoan(ctx context.Context, in *CreateMortgageLoanRequest, opts ...grpc.CallOption) (*CreateMortgageLoanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMortgageLoanReply)
	err := c.cc.Invoke(ctx, BookkeepingService_CreateMortgageLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) StartLoanRepayment(ctx context.Context, in *StartLoanRepaymentRequest, opts ...grpc.CallOption) (*StartLoanRepaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLoanRepaymentReply)
	err := c.cc.Invoke(ctx, BookkeepingService_StartLoanRepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) AdjustLoanRate(ctx context.Context, in *AdjustLoanRateRequest, opts ...grpc.CallOption) (*AdjustLoanRateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustLoanRateReply)
	err := c.cc.Invoke(ctx, BookkeepingService_AdjustLoanRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) AddLoanPrepayment(ctx context.Context, in *AddLoanPrepaymentRequest, opts ...grpc.CallOption) (*AddLoanPrepaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLoanPrepaymentReply)
	err := c.cc.Invoke(ctx, BookkeepingService_AddLoanPrepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) LoanSummaryList(ctx context.Context, in *LoanSummaryListRequest, opts ...grpc.CallOption) (*LoanSummaryListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanSummaryListReply)
	err := c.cc.Invoke(ctx, BookkeepingService_LoanSummaryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookkeepingServiceClient) LoanDetail(ctx context.Context, in *LoanDetailRequest, opts ...grpc.CallOption) (*LoanDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanDetailReply)
	err := c.cc.Invoke(ctx, BookkeepingService_LoanDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookkeepingServiceServer is the server API for BookkeepingService service.
// All implementations must embed UnimplementedBookkeepingServiceServer
// for forward compatibility.
type BookkeepingServiceServer interface {
	// 查询资产列表（按月份聚合，返回资产、负债、净资产及贷款明细）
	AssetList(context.Context, *AssetListRequest) (*AssetListReply, error)
	// 查询某月资产明细（若当月为空且上月存在，会自动复制一份上月数据到当月）
	AssetDetailList(context.Context, *AssetDetailListRequest) (*AssetDetailListReply, error)
	// 新增资产明细
	CreateAssetDetail(context.Context, *CreateAssetDetailRequest) (*CreateAssetDetailReply, error)
	// 更新资产明细
	UpdateAssetDetail(context.Context, *UpdateAssetDetailRequest) (*UpdateAssetDetailReply, error)
	// 删除资产明细
	DeleteAssetDetail(context.Context, *DeleteAssetDetailRequest) (*DeleteAssetDetailReply, error)
	// 更新某月资产备注
	UpdateAssetRemark(context.Context, *UpdateAssetRemarkRequest) (*UpdateAssetRemarkReply, error)
	// 新增或更新账本记录（按日期+类别+金额唯一更新）
	UpsertLedgerEntry(context.Context, *UpsertLedgerEntryRequest) (*UpsertLedgerEntryReply, error)
	// 查询某月账本清单
	LedgerList(context.Context, *LedgerListRequest) (*LedgerListReply, error)
	// 查询账单统计（支持按月/按年趋势与支出排行榜）
	LedgerStats(context.Context, *LedgerStatsRequest) (*LedgerStatsReply, error)
	// 创建房贷（等额本息）
	CreateMortgageLoan(context.Context, *CreateMortgageLoanRequest) (*CreateMortgageLoanReply, error)
	// 设置贷款开始还款时间
	StartLoanRepayment(context.Context, *StartLoanRepaymentRequest) (*StartLoanRepaymentReply, error)
	// 调整贷款利率（从指定年月起生效，重算后续还款计划）
	AdjustLoanRate(context.Context, *AdjustLoanRateRequest) (*AdjustLoanRateReply, error)
	// 新增提前还款记录（按指定方式重算后续还款计划）
	AddLoanPrepayment(context.Context, *AddLoanPrepaymentRequest) (*AddLoanPrepaymentReply, error)
	// 查询贷款汇总列表
	LoanSummaryList(context.Context, *LoanSummaryListRequest) (*LoanSummaryListReply, error)
	// 查询贷款详情（含下次还款日起未来N个月计划）
	LoanDetail(context.Context, *LoanDetailRequest) (*LoanDetailReply, error)
	mustEmbedUnimplementedBookkeepingServiceServer()
}

// UnimplementedBookkeepingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookkeepingServiceServer struct{}

func (UnimplementedBookkeepingServiceServer) AssetList(context.Context, *AssetListRequest) (*AssetListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AssetList not implemented")
}
func (UnimplementedBookkeepingServiceServer) AssetDetailList(context.Context, *AssetDetailListRequest) (*AssetDetailListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AssetDetailList not implemented")
}
func (UnimplementedBookkeepingServiceServer) CreateAssetDetail(context.Context, *CreateAssetDetailRequest) (*CreateAssetDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssetDetail not implemented")
}
func (UnimplementedBookkeepingServiceServer) UpdateAssetDetail(context.Context, *UpdateAssetDetailRequest) (*UpdateAssetDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssetDetail not implemented")
}
func (UnimplementedBookkeepingServiceServer) DeleteAssetDetail(context.Context, *DeleteAssetDetailRequest) (*DeleteAssetDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAssetDetail not implemented")
}
func (UnimplementedBookkeepingServiceServer) UpdateAssetRemark(context.Context, *UpdateAssetRemarkRequest) (*UpdateAssetRemarkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssetRemark not implemented")
}
func (UnimplementedBookkeepingServiceServer) UpsertLedgerEntry(context.Context, *UpsertLedgerEntryRequest) (*UpsertLedgerEntryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertLedgerEntry not implemented")
}
func (UnimplementedBookkeepingServiceServer) LedgerList(context.Context, *LedgerListRequest) (*LedgerListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LedgerList not implemented")
}
func (UnimplementedBookkeepingServiceServer) LedgerStats(context.Context, *LedgerStatsRequest) (*LedgerStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LedgerStats not implemented")
}
func (UnimplementedBookkeepingServiceServer) CreateMortgageLoan(context.Context, *CreateMortgageLoanRequest) (*CreateMortgageLoanReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMortgageLoan not implemented")
}
func (UnimplementedBookkeepingServiceServer) StartLoanRepayment(context.Context, *StartLoanRepaymentRequest) (*StartLoanRepaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLoanRepayment not implemented")
}
func (UnimplementedBookkeepingServiceServer) AdjustLoanRate(context.Context, *AdjustLoanRateRequest) (*AdjustLoanRateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustLoanRate not implemented")
}
func (UnimplementedBookkeepingServiceServer) AddLoanPrepayment(context.Context, *AddLoanPrepaymentRequest) (*AddLoanPrepaymentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLoanPrepayment not implemented")
}
func (UnimplementedBookkeepingServiceServer) LoanSummaryList(context.Context, *LoanSummaryListRequest) (*LoanSummaryListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LoanSummaryList not implemented")
}
func (UnimplementedBookkeepingServiceServer) LoanDetail(context.Context, *LoanDetailRequest) (*LoanDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LoanDetail not implemented")
}
func (UnimplementedBookkeepingServiceServer) mustEmbedUnimplementedBookkeepingServiceServer() {}
func (UnimplementedBookkeepingServiceServer) testEmbeddedByValue()                            {}

// UnsafeBookkeepingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookkeepingServiceServer will
// result in compilation errors.
type UnsafeBookkeepingServiceServer interface {
	mustEmbedUnimplementedBookkeepingServiceServer()
}

func RegisterBookkeepingServiceServer(s grpc.ServiceRegistrar, srv BookkeepingServiceServer) {
	// If the following call panics, it indicates UnimplementedBookkeepingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookkeepingService_ServiceDesc, srv)
}

func _BookkeepingService_AssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).AssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_AssetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).AssetList(ctx, req.(*AssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_AssetDetailList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetDetailListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).AssetDetailList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_AssetDetailList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).AssetDetailList(ctx, req.(*AssetDetailListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_CreateAssetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).CreateAssetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_CreateAssetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).CreateAssetDetail(ctx, req.(*CreateAssetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_UpdateAssetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).UpdateAssetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_UpdateAssetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).UpdateAssetDetail(ctx, req.(*UpdateAssetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_DeleteAssetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).DeleteAssetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_DeleteAssetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).DeleteAssetDetail(ctx, req.(*DeleteAssetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_UpdateAssetRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRemarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).UpdateAssetRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_UpdateAssetRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).UpdateAssetRemark(ctx, req.(*UpdateAssetRemarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_UpsertLedgerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertLedgerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).UpsertLedgerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_UpsertLedgerEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).UpsertLedgerEntry(ctx, req.(*UpsertLedgerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_LedgerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).LedgerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_LedgerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).LedgerList(ctx, req.(*LedgerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_LedgerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).LedgerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_LedgerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).LedgerStats(ctx, req.(*LedgerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_CreateMortgageLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMortgageLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).CreateMortgageLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_CreateMortgageLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).CreateMortgageLoan(ctx, req.(*CreateMortgageLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_StartLoanRepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLoanRepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).StartLoanRepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_StartLoanRepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).StartLoanRepayment(ctx, req.(*StartLoanRepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_AdjustLoanRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustLoanRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).AdjustLoanRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_AdjustLoanRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).AdjustLoanRate(ctx, req.(*AdjustLoanRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_AddLoanPrepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLoanPrepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).AddLoanPrepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_AddLoanPrepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).AddLoanPrepayment(ctx, req.(*AddLoanPrepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_LoanSummaryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanSummaryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).LoanSummaryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_LoanSummaryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).LoanSummaryList(ctx, req.(*LoanSummaryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookkeepingService_LoanDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookkeepingServiceServer).LoanDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookkeepingService_LoanDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookkeepingServiceServer).LoanDetail(ctx, req.(*LoanDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookkeepingService_ServiceDesc is the grpc.ServiceDesc for BookkeepingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookkeepingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bookkeeping.v1.BookkeepingService",
	HandlerType: (*BookkeepingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssetList",
			Handler:    _BookkeepingService_AssetList_Handler,
		},
		{
			MethodName: "AssetDetailList",
			Handler:    _BookkeepingService_AssetDetailList_Handler,
		},
		{
			MethodName: "CreateAssetDetail",
			Handler:    _BookkeepingService_CreateAssetDetail_Handler,
		},
		{
			MethodName: "UpdateAssetDetail",
			Handler:    _BookkeepingService_UpdateAssetDetail_Handler,
		},
		{
			MethodName: "DeleteAssetDetail",
			Handler:    _BookkeepingService_DeleteAssetDetail_Handler,
		},
		{
			MethodName: "UpdateAssetRemark",
			Handler:    _BookkeepingService_UpdateAssetRemark_Handler,
		},
		{
			MethodName: "UpsertLedgerEntry",
			Handler:    _BookkeepingService_UpsertLedgerEntry_Handler,
		},
		{
			MethodName: "LedgerList",
			Handler:    _BookkeepingService_LedgerList_Handler,
		},
		{
			MethodName: "LedgerStats",
			Handler:    _BookkeepingService_LedgerStats_Handler,
		},
		{
			MethodName: "CreateMortgageLoan",
			Handler:    _BookkeepingService_CreateMortgageLoan_Handler,
		},
		{
			MethodName: "StartLoanRepayment",
			Handler:    _BookkeepingService_StartLoanRepayment_Handler,
		},
		{
			MethodName: "AdjustLoanRate",
			Handler:    _BookkeepingService_AdjustLoanRate_Handler,
		},
		{
			MethodName: "AddLoanPrepayment",
			Handler:    _BookkeepingService_AddLoanPrepayment_Handler,
		},
		{
			MethodName: "LoanSummaryList",
			Handler:    _BookkeepingService_LoanSummaryList_Handler,
		},
		{
			MethodName: "LoanDetail",
			Handler:    _BookkeepingService_LoanDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/bookkeeping/v1/bookkeeping.proto",
}
