syntax = "proto3";
package app_layout.api;

option go_package = "github.com/jeffinity/oculus/app/app_layout/internal/conf";

import "google/protobuf/duration.proto";
import "logx/entity/logx.proto";

message Bootstrap {

  Server server = 1;
  oculus.api.logx.LogOpt log = 2;

  Postgres postgres = 3;
  Redis redis = 4;
  OSS oss = 5;
}

message ServerInfo {
  string name = 1;
  string host = 2;
  int32 port = 3;
}

message Registry {
  repeated ServerInfo server_list = 1;
}

message Server {
  string addr = 1;
  google.protobuf.Duration timeout = 2;
}

message Postgres {
  string dsn = 1;
}

message Redis {
  string dsn = 1;
}

message OSS {
  string endpoint = 1;
  string access_key = 2;
  string secret_key = 3;
  string bucket = 5; // 存储数据默认 bucket
}