// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	Mcp           *MCP                   `protobuf:"bytes,2,opt,name=mcp,proto3" json:"mcp,omitempty"`
	Eks           []*EKSCluster          `protobuf:"bytes,3,rep,name=eks,proto3" json:"eks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetMcp() *MCP {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *Bootstrap) GetEks() []*EKSCluster {
	if x != nil {
		return x.Eks
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisableStdLog bool                   `protobuf:"varint,1,opt,name=disable_std_log,json=disableStdLog,proto3" json:"disable_std_log,omitempty"`
	LogDir        string                 `protobuf:"bytes,2,opt,name=log_dir,json=logDir,proto3" json:"log_dir,omitempty"`
	LogFilename   string                 `protobuf:"bytes,3,opt,name=log_filename,json=logFilename,proto3" json:"log_filename,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	MaxSizeMb     int32                  `protobuf:"varint,10,opt,name=max_size_mb,json=maxSizeMb,proto3" json:"max_size_mb,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,11,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAgeDays    int32                  `protobuf:"varint,12,opt,name=max_age_days,json=maxAgeDays,proto3" json:"max_age_days,omitempty"`
	Compress      bool                   `protobuf:"varint,13,opt,name=compress,proto3" json:"compress,omitempty"`
	RotateDaily   bool                   `protobuf:"varint,14,opt,name=rotate_daily,json=rotateDaily,proto3" json:"rotate_daily,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetDisableStdLog() bool {
	if x != nil {
		return x.DisableStdLog
	}
	return false
}

func (x *Log) GetLogDir() string {
	if x != nil {
		return x.LogDir
	}
	return ""
}

func (x *Log) GetLogFilename() string {
	if x != nil {
		return x.LogFilename
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMaxSizeMb() int32 {
	if x != nil {
		return x.MaxSizeMb
	}
	return 0
}

func (x *Log) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Log) GetMaxAgeDays() int32 {
	if x != nil {
		return x.MaxAgeDays
	}
	return 0
}

func (x *Log) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

func (x *Log) GetRotateDaily() bool {
	if x != nil {
		return x.RotateDaily
	}
	return false
}

type MCP struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ServerName            string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion         string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	MaxOutputBytes        int32                  `protobuf:"varint,3,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	MaxConcurrentRequests int32                  `protobuf:"varint,4,opt,name=max_concurrent_requests,json=maxConcurrentRequests,proto3" json:"max_concurrent_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MCP) Reset() {
	*x = MCP{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCP) ProtoMessage() {}

func (x *MCP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCP.ProtoReflect.Descriptor instead.
func (*MCP) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *MCP) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *MCP) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *MCP) GetMaxOutputBytes() int32 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *MCP) GetMaxConcurrentRequests() int32 {
	if x != nil {
		return x.MaxConcurrentRequests
	}
	return 0
}

type EKSCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Jumpserver    *JumpServer            `protobuf:"bytes,2,opt,name=jumpserver,proto3" json:"jumpserver,omitempty"`
	Envs          []*EKSEnv              `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKSCluster) Reset() {
	*x = EKSCluster{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKSCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKSCluster) ProtoMessage() {}

func (x *EKSCluster) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKSCluster.ProtoReflect.Descriptor instead.
func (*EKSCluster) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *EKSCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EKSCluster) GetJumpserver() *JumpServer {
	if x != nil {
		return x.Jumpserver
	}
	return nil
}

func (x *EKSCluster) GetEnvs() []*EKSEnv {
	if x != nil {
		return x.Envs
	}
	return nil
}

type JumpServer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Host                  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                  uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User                  string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	IdentityFile          string                 `protobuf:"bytes,4,opt,name=identity_file,json=identityFile,proto3" json:"identity_file,omitempty"`
	IdentityPassphraseEnv string                 `protobuf:"bytes,5,opt,name=identity_passphrase_env,json=identityPassphraseEnv,proto3" json:"identity_passphrase_env,omitempty"`
	Socks5Proxy           string                 `protobuf:"bytes,6,opt,name=socks5_proxy,json=socks5Proxy,proto3" json:"socks5_proxy,omitempty"`
	InsecureIgnoreHostKey bool                   `protobuf:"varint,7,opt,name=insecure_ignore_host_key,json=insecureIgnoreHostKey,proto3" json:"insecure_ignore_host_key,omitempty"`
	ConnectTimeout        *durationpb.Duration   `protobuf:"bytes,8,opt,name=connect_timeout,json=connectTimeout,proto3" json:"connect_timeout,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JumpServer) Reset() {
	*x = JumpServer{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JumpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JumpServer) ProtoMessage() {}

func (x *JumpServer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JumpServer.ProtoReflect.Descriptor instead.
func (*JumpServer) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *JumpServer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *JumpServer) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *JumpServer) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *JumpServer) GetIdentityFile() string {
	if x != nil {
		return x.IdentityFile
	}
	return ""
}

func (x *JumpServer) GetIdentityPassphraseEnv() string {
	if x != nil {
		return x.IdentityPassphraseEnv
	}
	return ""
}

func (x *JumpServer) GetSocks5Proxy() string {
	if x != nil {
		return x.Socks5Proxy
	}
	return ""
}

func (x *JumpServer) GetInsecureIgnoreHostKey() bool {
	if x != nil {
		return x.InsecureIgnoreHostKey
	}
	return false
}

func (x *JumpServer) GetConnectTimeout() *durationpb.Duration {
	if x != nil {
		return x.ConnectTimeout
	}
	return nil
}

type Pool struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MinSize             int32                  `protobuf:"varint,1,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	MaxSize             int32                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	CommandTimeout      *durationpb.Duration   `protobuf:"bytes,3,opt,name=command_timeout,json=commandTimeout,proto3" json:"command_timeout,omitempty"`
	IdleTtl             *durationpb.Duration   `protobuf:"bytes,4,opt,name=idle_ttl,json=idleTtl,proto3" json:"idle_ttl,omitempty"`
	HealthCheckInterval *durationpb.Duration   `protobuf:"bytes,5,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	HealthCheckTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=health_check_timeout,json=healthCheckTimeout,proto3" json:"health_check_timeout,omitempty"`
	HealthCheckCommand  string                 `protobuf:"bytes,7,opt,name=health_check_command,json=healthCheckCommand,proto3" json:"health_check_command,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Pool) GetMinSize() int32 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *Pool) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Pool) GetCommandTimeout() *durationpb.Duration {
	if x != nil {
		return x.CommandTimeout
	}
	return nil
}

func (x *Pool) GetIdleTtl() *durationpb.Duration {
	if x != nil {
		return x.IdleTtl
	}
	return nil
}

func (x *Pool) GetHealthCheckInterval() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckInterval
	}
	return nil
}

func (x *Pool) GetHealthCheckTimeout() *durationpb.Duration {
	if x != nil {
		return x.HealthCheckTimeout
	}
	return nil
}

func (x *Pool) GetHealthCheckCommand() string {
	if x != nil {
		return x.HealthCheckCommand
	}
	return ""
}

type EKSEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	OptPrompt     string                 `protobuf:"bytes,3,opt,name=opt_prompt,json=optPrompt,proto3" json:"opt_prompt,omitempty"`
	ShellPrompt   string                 `protobuf:"bytes,4,opt,name=shell_prompt,json=shellPrompt,proto3" json:"shell_prompt,omitempty"`
	QueryPool     *Pool                  `protobuf:"bytes,5,opt,name=query_pool,json=queryPool,proto3" json:"query_pool,omitempty"`
	DeployPool    *Pool                  `protobuf:"bytes,6,opt,name=deploy_pool,json=deployPool,proto3" json:"deploy_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKSEnv) Reset() {
	*x = EKSEnv{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKSEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKSEnv) ProtoMessage() {}

func (x *EKSEnv) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKSEnv.ProtoReflect.Descriptor instead.
func (*EKSEnv) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{6}
}

func (x *EKSEnv) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EKSEnv) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *EKSEnv) GetOptPrompt() string {
	if x != nil {
		return x.OptPrompt
	}
	return ""
}

func (x *EKSEnv) GetShellPrompt() string {
	if x != nil {
		return x.ShellPrompt
	}
	return ""
}

func (x *EKSEnv) GetQueryPool() *Pool {
	if x != nil {
		return x.QueryPool
	}
	return nil
}

func (x *EKSEnv) GetDeployPool() *Pool {
	if x != nil {
		return x.DeployPool
	}
	return nil
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x0eapp.eks_server\x1a\x1egoogle/protobuf/duration.proto\"\x87\x01\n" +
	"\tBootstrap\x12%\n" +
	"\x03log\x18\x01 \x01(\v2\x13.app.eks_server.LogR\x03log\x12%\n" +
	"\x03mcp\x18\x02 \x01(\v2\x13.app.eks_server.MCPR\x03mcp\x12,\n" +
	"\x03eks\x18\x03 \x03(\v2\x1a.app.eks_server.EKSClusterR\x03eks\"\xa1\x02\n" +
	"\x03Log\x12&\n" +
	"\x0fdisable_std_log\x18\x01 \x01(\bR\rdisableStdLog\x12\x17\n" +
	"\alog_dir\x18\x02 \x01(\tR\x06logDir\x12!\n" +
	"\flog_filename\x18\x03 \x01(\tR\vlogFilename\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x1e\n" +
	"\vmax_size_mb\x18\n" +
	" \x01(\x05R\tmaxSizeMb\x12\x1f\n" +
	"\vmax_backups\x18\v \x01(\x05R\n" +
	"maxBackups\x12 \n" +
	"\fmax_age_days\x18\f \x01(\x05R\n" +
	"maxAgeDays\x12\x1a\n" +
	"\bcompress\x18\r \x01(\bR\bcompress\x12!\n" +
	"\frotate_daily\x18\x0e \x01(\bR\vrotateDaily\"\xaf\x01\n" +
	"\x03MCP\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12(\n" +
	"\x10max_output_bytes\x18\x03 \x01(\x05R\x0emaxOutputBytes\x126\n" +
	"\x17max_concurrent_requests\x18\x04 \x01(\x05R\x15maxConcurrentRequests\"\x88\x01\n" +
	"\n" +
	"EKSCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\n" +
	"jumpserver\x18\x02 \x01(\v2\x1a.app.eks_server.JumpServerR\n" +
	"jumpserver\x12*\n" +
	"\x04envs\x18\x03 \x03(\v2\x16.app.eks_server.EKSEnvR\x04envs\"\xc5\x02\n" +
	"\n" +
	"JumpServer\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12#\n" +
	"\ridentity_file\x18\x04 \x01(\tR\fidentityFile\x126\n" +
	"\x17identity_passphrase_env\x18\x05 \x01(\tR\x15identityPassphraseEnv\x12!\n" +
	"\fsocks5_proxy\x18\x06 \x01(\tR\vsocks5Proxy\x127\n" +
	"\x18insecure_ignore_host_key\x18\a \x01(\bR\x15insecureIgnoreHostKey\x12B\n" +
	"\x0fconnect_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\x0econnectTimeout\"\x84\x03\n" +
	"\x04Pool\x12\x19\n" +
	"\bmin_size\x18\x01 \x01(\x05R\aminSize\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x05R\amaxSize\x12B\n" +
	"\x0fcommand_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0ecommandTimeout\x124\n" +
	"\bidle_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\aidleTtl\x12M\n" +
	"\x15health_check_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x13healthCheckInterval\x12K\n" +
	"\x14health_check_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x12healthCheckTimeout\x120\n" +
	"\x14health_check_command\x18\a \x01(\tR\x12healthCheckCommand\"\xe0\x01\n" +
	"\x06EKSEnv\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x1d\n" +
	"\n" +
	"opt_prompt\x18\x03 \x01(\tR\toptPrompt\x12!\n" +
	"\fshell_prompt\x18\x04 \x01(\tR\vshellPrompt\x123\n" +
	"\n" +
	"query_pool\x18\x05 \x01(\v2\x14.app.eks_server.PoolR\tqueryPool\x125\n" +
	"\vdeploy_pool\x18\x06 \x01(\v2\x14.app.eks_server.PoolR\n" +
	"deployPoolB\x0fZ\rinternal/confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: app.eks_server.Bootstrap
	(*Log)(nil),                 // 1: app.eks_server.Log
	(*MCP)(nil),                 // 2: app.eks_server.MCP
	(*EKSCluster)(nil),          // 3: app.eks_server.EKSCluster
	(*JumpServer)(nil),          // 4: app.eks_server.JumpServer
	(*Pool)(nil),                // 5: app.eks_server.Pool
	(*EKSEnv)(nil),              // 6: app.eks_server.EKSEnv
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: app.eks_server.Bootstrap.log:type_name -> app.eks_server.Log
	2,  // 1: app.eks_server.Bootstrap.mcp:type_name -> app.eks_server.MCP
	3,  // 2: app.eks_server.Bootstrap.eks:type_name -> app.eks_server.EKSCluster
	4,  // 3: app.eks_server.EKSCluster.jumpserver:type_name -> app.eks_server.JumpServer
	6,  // 4: app.eks_server.EKSCluster.envs:type_name -> app.eks_server.EKSEnv
	7,  // 5: app.eks_server.JumpServer.connect_timeout:type_name -> google.protobuf.Duration
	7,  // 6: app.eks_server.Pool.command_timeout:type_name -> google.protobuf.Duration
	7,  // 7: app.eks_server.Pool.idle_ttl:type_name -> google.protobuf.Duration
	7,  // 8: app.eks_server.Pool.health_check_interval:type_name -> google.protobuf.Duration
	7,  // 9: app.eks_server.Pool.health_check_timeout:type_name -> google.protobuf.Duration
	5,  // 10: app.eks_server.EKSEnv.query_pool:type_name -> app.eks_server.Pool
	5,  // 11: app.eks_server.EKSEnv.deploy_pool:type_name -> app.eks_server.Pool
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
